### ISSUE TITLE
请问，有人训练成功了吗？

### ISSUE THREAD

**Issue by AImagicAI** [KyanChen/RSPrompter#100]
我使用官方数据集，迭代几次后，出现loss=Nan的情况；

然后我训练自己数据集的时候（labelme标注的数据集，转为了coco格式），出现以下情况：
![图片](https://github.com/KyanChen/RSPrompter/assets/164443911/075bcf36-e9d1-4158-b39f-ec97b557c5b9)

**Comment by hailongm** [comment]
> 我使用官方数据集，迭代几次后，出现loss=Nan的情况；
> 
> 然后我训练自己数据集的时候（labelme标注的数据集，转为了coco格式），出现以下情况： ![图片](https://private-user-images.githubusercontent.com/164443911/321894672-075bcf36-e9d1-4158-b39f-ec97b557c5b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDYxNTIsIm5iZiI6MTcxMjkwNTg1MiwicGF0aCI6Ii8xNjQ0NDM5MTEvMzIxODk0NjcyLTA3NWJjZjM2LWU5ZDEtNDE1OC1iMzlmLWVjOTdiNTU3YzViOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQwNzEwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YWQ0OTE3ZGI3YTlkNDM5NTdlNWU3OWMyNjg1NDc4MDdiODRjNzA1YmVlNjYyZTg4NzM1MjZkODBiMDA5OTdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cxgVxXwPTZqRpGyK5Vi564IYx65Dv4WENpFOJ2OQOGs)

你预测成功了吗，我训练了几轮，还没注意到你这个问题，但是我预测没成功

**Comment by AImagicAI** [comment]
我还未预测，您使用自己数据集训练的吗？

**Comment by hailongm** [comment]
我是用的官方数据集，您能先预测看一下效果吗，我没有预测成功

**Comment by AImagicAI** [comment]
这个预测的权重文件有吗？我没有在项目里找到权重

**Comment by hailongm** [comment]
我用自己跑的checkpoint尝试运行的

**Comment by hailongm** [comment]
1002582248，可以添加后联系一下

**Comment by AImagicAI** [comment]
我训练有问题，您是用的哪个数据集？SSDD？

**Comment by hailongm** [comment]
是的

**Comment by YeeCharm** [comment]
我用的作者给的裁剪的NWPU_512那个代码跑的，跑了五百轮，没啥问题，但是最后测试的mask分割指标差的有点多
![Uploading 1280X1280.PNG…]()

**Comment by AImagicAI** [comment]
跑的自己的数据集吗？


                       
原始邮件
                       
                     

发件人："YeeCharm"< ***@***.*** &gt;;

发件时间：2024/4/17 16:48

收件人："KyanChen/RSPrompter"< ***@***.*** &gt;;

抄送人："AImagicAI"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [KyanChen/RSPrompter] 请问，有人训练成功了吗？ (Issue #100)




 
我用的作者给的裁剪的NWPU_512那个代码跑的，跑了五百轮，没啥问题，但是最后测试的mask分割指标差的有点多

**Comment by YeeCharm** [comment]
就是下载下来data里面作者放的NWPU那650张图片跑的，但是我用NWPU_anchor跑几十轮就也是会出现loss的NaN，WHU和SSDD数据集都遇到这种情况了

**Comment by youcandoitooo** [comment]
兄弟们，我想知道hf_sam_pretrain_name这个里面用到的sam这个怎么弄啊

**Comment by YeeCharm** [comment]
> 兄弟们，我想知道hf_sam_pretrain_name这个里面用到的sam这个怎么弄啊

好兄弟，我在官网下载的(https://huggingface.co/facebook/sam-vit-base/tree/main)，你把那几个文件一个一个下载下来，然后在work_dirs文件夹下建一个sam_cache文件夹，在sam_cache再建一个sam_vit_base文件夹，把下载的文件都放里头就行

**Comment by ymkasad** [comment]
这个nan有办法解决吗

**Comment by KyanChen** [comment]
fixed: 请查看QA中的第6条。见 https://github.com/KyanChen/RSPrompter/blob/release/README_zh-CN.md

**Comment by liwead** [comment]
> > 兄弟们，我想知道hf_sam_pretrain_name这个里面用到的sam这个怎么弄啊
> 
> 好兄弟，我在官网下载的([https://huggingface.co/facebook/sam-vit-base/tree/main)，你把那几个文件一个一个下载下来，然后在work_dirs文件夹下建一个sam_cache文件夹，在sam_cache再建一个sam_vit_base文件夹，把下载的文件都放里头就行](https://huggingface.co/facebook/sam-vit-base/tree/main)%EF%BC%8C%E4%BD%A0%E6%8A%8A%E9%82%A3%E5%87%A0%E4%B8%AA%E6%96%87%E4%BB%B6%E4%B8%80%E4%B8%AA%E4%B8%80%E4%B8%AA%E4%B8%8B%E8%BD%BD%E4%B8%8B%E6%9D%A5%EF%BC%8C%E7%84%B6%E5%90%8E%E5%9C%A8work_dirs%E6%96%87%E4%BB%B6%E5%A4%B9%E4%B8%8B%E5%BB%BA%E4%B8%80%E4%B8%AAsam_cache%E6%96%87%E4%BB%B6%E5%A4%B9%EF%BC%8C%E5%9C%A8sam_cache%E5%86%8D%E5%BB%BA%E4%B8%80%E4%B8%AAsam_vit_base%E6%96%87%E4%BB%B6%E5%A4%B9%EF%BC%8C%E6%8A%8A%E4%B8%8B%E8%BD%BD%E7%9A%84%E6%96%87%E4%BB%B6%E9%83%BD%E6%94%BE%E9%87%8C%E5%A4%B4%E5%B0%B1%E8%A1%8C)

兄弟，我按照你所说的下载好了sam_vit_base，然后运行代码时提示我需要下载sam_vit_huge，我也是在sam_cache创建了一个sam_vit_huge文件夹，然后去https://huggingface.co/facebook/sam-vit-huge/tree/main 把相关文件放进去，但是仍旧提示找不到sam_vit_huge

**Comment by liwead** [comment]
> > 兄弟们，我想知道hf_sam_pretrain_name这个里面用到的sam这个怎么弄啊
> 
> 好兄弟，我在官网下载的([https://huggingface.co/facebook/sam-vit-base/tree/main)，你把那几个文件一个一个下载下来，然后在work_dirs文件夹下建一个sam_cache文件夹，在sam_cache再建一个sam_vit_base文件夹，把下载的文件都放里头就行](https://huggingface.co/facebook/sam-vit-base/tree/main)

兄弟，我按照你所说的下载好了sam_vit_base，然后运行代码时提示我需要下载sam_vit_huge，我也是在sam_cache创建了一个sam_vit_huge文件夹，然后去https://huggingface.co/facebook/sam-vit-huge/tree/main 把相关文件放进去，但是仍旧提示找不到sam_vit_huge
