### ISSUE TITLE
请问有人能提供一下checkpoint吗

### ISSUE THREAD

**Issue by Graysonggg** [KyanChen/RSPrompter#101]
请问有人能提供一下checkpoint吗

**Comment by Graysonggg** [comment]
自己训练的也行

**Comment by dly61** [comment]
我可以分享给你

**Comment by HorneYang** [comment]
> 我可以分享给你

可以也分享一份给我吗？

**Comment by dly61** [comment]
加我qq1827557787我发邮箱给你

**Comment by KyanChen** [comment]
fixed: 请查看QA中的第6条。见 https://github.com/KyanChen/RSPrompter/blob/release/README_zh-CN.md

**Comment by Arandinglv** [comment]
> 加我qq1827557787我发邮箱给你

您好，我的邮箱是arandinglv@gmail.com，请问可以麻烦您发一下checkpoint吗？

**Comment by monument-and-sea-all-the-gift** [comment]
> 加我qq1827557787我发邮箱给你

您好，我的邮箱是2763362488@qq.com，请问可以麻烦您发一下checkpoint吗？

**Comment by meiqihu** [comment]
您好，我的邮箱是1345828035@qq.com,请问可以麻烦您发一下RSPrompter_query的checkpoint吗，几种数据集的都可以，非常感谢❤️
