### ISSUE TITLE
为什么anchor_whu这个文件训练出来模型测试时候seg_map的一些指标都为0啊？

### ISSUE THREAD

**Issue by ausch11** [KyanChen/RSPrompter#103]
![{43E247B1-4BA7-4f0d-B8DF-FFF294B8673D}](https://github.com/KyanChen/RSPrompter/assets/139742698/4d94251c-efda-4611-b7ea-f7b4c351bca1)
这是测试完的文件，关于分割一些指标都为0。查看可视化结果，就是图片上只有框没有进行分割
![QQ截图20240424161806](https://github.com/KyanChen/RSPrompter/assets/139742698/5988e1d0-eaac-43bb-abb4-8e4ed0728c94)

**Comment by DAIJinJ** [comment]
同问

**Comment by funny000** [comment]
你好@ausch11，
你训练的时候box框的误差、分割的误差都为零吗

**Comment by ausch11** [comment]
> 你好@ausch11， 你训练的时候box框的误差、分割的误差都为零吗

不为0

**Comment by ymkasad** [comment]
你好，请问这个是模型测试test.py还是图像预测image_demo.py的结果呢

**Comment by kadvinj** [comment]
因为这个anchor model weight的seg部分没有预测出mask，只有rpn出来额box

**Comment by funny000** [comment]
@ausch11楼主现在解决这个问题了吗，我理解应该是和@kadvinj一样，但问题是为什么没有预测出来seg，会不会和训练的时候seg的损失一直为零有关系

**Comment by ausch11** [comment]
> 你好，请问这个是模型测试test.py还是图像预测image_demo.py的结果呢

test的结果。不过已经解决了，应该是模型训练有误。

**Comment by ausch11** [comment]
> @ausch11楼主现在解决这个问题了吗，我理解应该是和@kadvinj一样，但问题是为什么没有预测出来seg，会不会和训练的时候seg的损失一直为零有关系

对的。之前是训练的模型有问题。

**Comment by KyanChen** [comment]
fixed: 请查看QA中的第6条。见 https://github.com/KyanChen/RSPrompter/blob/release/README_zh-CN.md
