### ISSUE TITLE
关于环境配置

### ISSUE THREAD

**Issue by go1314** [KyanChen/RSPrompter#11]
在python3.10下，兼容pycocotools什么版本，最新的好像只兼容3.8。我安装了pycocotools后，在运行时，可以导入pycocotools但无法导入pycocotools._mask。求解答

**Comment by KyanChen** [comment]
我采用pip安装的，可以使用python3.10

**Comment by go1314** [comment]
感谢！可以了！做了好多尝试，原来pip就可以。
