### ISSUE TITLE
confused about the "Model Evaluation" There is no test_step function in `SegSAMAnchorPLer`

### ISSUE THREAD

**Issue by dongwhfdyer** [KyanChen/RSPrompter#12]
As you mentioned, use `python tools/test.py` to do model evaluation. There is even no test_step function in the model `SegSAMAnchorPLer` definition.

![image](https://github.com/KyanChen/RSPrompter/assets/59996817/a7448689-6737-4dd7-b0cf-eca6af973e9f)

(actually, There are many other things I cannot understand in your readme file.😭

**Comment by KyanChen** [comment]
Fixed it. Seeing [seg_sam_anchor_pler](https://github.com/KyanChen/RSPrompter/blob/cky/mmpl/models/pler/seg_sam_anchor_pler.py), Line 99.
