### ISSUE TITLE
KeyError: 'pytorch-lightning_version'

### ISSUE THREAD

**Issue by dongwhfdyer** [KyanChen/RSPrompter#13]
When `python tools/test.py`, it prompts this error.

![image](https://github.com/KyanChen/RSPrompter/assets/59996817/93e4804c-aa9e-4f4c-87e1-71d0d996f665)

![image](https://github.com/KyanChen/RSPrompter/assets/59996817/91ae1f3c-55b5-403e-9dd1-e7c846342a97)

**Comment by KyanChen** [comment]
You can try the hugging face demo, the App_main.py file.
when using python to run test.py, it requires the ckpt trained by yourself.
The trained pth only contains the model parameters, not containing other meta-information.
