### ISSUE TITLE
Unable to download datasets

### ISSUE THREAD

**Issue by sandeepjana** [KyanChen/RSPrompter#14]
I get "This site can’t be reached" when trying to download the three datasets using the links in the README file. Any alternative way to download the datasets? Thanks!

**Comment by KyanChen** [comment]
You can try to search the dataset in google or github. It will offer the link to download.

**Comment by sandeepjana** [comment]
Thanks... https://github.com/chaozhong2010/VHR-10_dataset_coco has NWPU and SSDD datasets
