### ISSUE TITLE
Verify the result visualization

### ISSUE THREAD

**Issue by ZhaoPo** [KyanChen/RSPrompter#15]
Hello, please ask me the following two questions again:
(1) How to visualize results on validation sets after running python/tools/predict.py. Where are the results saved? Does the code have an inference part? After I run it as follows:
Loaded model weights from the checkpoint at /home/zhaopo/SAM/SAM_SSDD/RSPrompter-cky/results/ssdd_ins/7.7/checkpoints/epoch_epoch=9-map_valsegm_map_0=0.6500.ckpt
Predicting DataLoader 0: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 232/232 [01:18<00:00,  2.96it/s]

(2) Are these indicators normal after I run 10 rounds：
wandb:       valbbox_map_0 0.55
wandb:    valbbox_map_50_0 1.0
wandb:    valbbox_map_75_0 0.505
wandb:     valbbox_map_l_0 -1.0
wandb:     valbbox_map_m_0 0.55
wandb:     valbbox_map_s_0 -1.0
wandb:       valsegm_map_0 0.65
wandb:    valsegm_map_50_0 1.0
wandb:    valsegm_map_75_0 1.0
wandb:     valsegm_map_l_0 -1.0
wandb:     valsegm_map_m_0 0.65
wandb:     valsegm_map_s_0 -1.0

**Comment by KyanChen** [comment]
1. To see the results, please refer to the callback cfg parameter settings in the predict cfg file.
2. What type of method do you try?

**Comment by ZhaoPo** [comment]
Thanks for the reply, I am trying to run:
     rsprompter_anchor_ssdd_config.py
