### ISSUE TITLE
Where is the ”sam_vit_h_4b8939.pth file“

### ISSUE THREAD

**Issue by Jasper0068** [KyanChen/RSPrompter#17]
Thanks for your contribution, I was experimenting with python train.py and encountered the following error
No such file or directory: 'pretrain/sam/sam_vit_h_4b8939.pth'
I didn't find it in the project file either, where is it please?
Good luck!

**Comment by KyanChen** [comment]
download it from the official sam repository

**Comment by Jasper0068** [comment]
Ok thank you!
