### ISSUE TITLE
How to save checkpoints and visualize during training?

### ISSUE THREAD

**Issue by JaireYu** [KyanChen/RSPrompter#18]
Wonderful job! I run the code with the default config on WHU dataset. However, after 2 epochs the evaluation results are still 0.0000. There are no vis masks and no checkpoints can be used to predict. Do you have any idea about save checkpoints and visualize during training?

**Comment by KyanChen** [comment]
What type of method do you train on?

**Comment by JaireYu** [comment]
I reproduced the experiment mainly based on rsprompter_anchor_whu_config.py. The running script is:
python tools/train.py --config configs/rsprompter_anchor_whu_config.py.
should I add some ckpt saving config or visualization config in the config file?

**Comment by mmmll23** [comment]
I also encountered this problem.  Did I miss some details during training? How should I solve it? Thank you.
