### ISSUE TITLE
about SAM-det and SAM-cls

### ISSUE THREAD

**Issue by GallonDeng** [KyanChen/RSPrompter#2]
Nice work. In the results table, it was not mentioned the details about the implementations of SAM-det and SAM-cls, any reference？

**Comment by KyanChen** [comment]
SAM-det: First using Faster-RCNN to detect; then using the box as a prompt for segmentation
SAM-cls: First using "everything" mode to segment anything; then use resnet18 (trained with label) to classify
For more detail, please refer to our codes.
SAM-det: https://github.com/KyanChen/RSPrompter/blob/cky/configs/rsprompter/samdet_fasterrcnn_whu_config.py
SAM-csl: https://github.com/KyanChen/RSPrompter/blob/cky/tools/ins_seg/sam/sam_cls/get_sam_cls_crops.py
