### ISSUE TITLE
Cannot load ".pth" trained model file provided in this code.

### ISSUE THREAD

**Issue by zfbi** [KyanChen/RSPrompter#20]
The pre-trained model you provided with the ".pth" file extension cannot be loaded during the model inference stage. Could you please provide the corresponding pre-trained model in .ckpt format?

**Comment by zfbi** [comment]
I attempted to load the training parameters from "SSDD_anchor.pth" into the initial model "SAMAnchorInstanceHead," but encountered an error: RuntimeError: Error(s) in loading state_dict for SegSAMAnchorPLer:

> size mismatch for panoptic_head.roi_head.mask_head.point_emb.8.weight: copying a parameter with shape torch.Size([2560, 256]) from the checkpoint, while the shape in the current model is torch.Size([2048, 256]).
> size mismatch for panoptic_head.roi_head.mask_head.point_emb.8.bias: copying a parameter with shape torch.Size([2560]) from the checkpoint, while the shape in the current model is torch.Size([2048]).

Could you please advise on how to resolve this mismatch issue? Alternatively, is it possible to obtain a compatible version of the pre-trained model in .ckpt format?

**Comment by KyanChen** [comment]
The pth file only contains the state_dict of the model, not containing meta information. You can try the App_main.py in the huggingface demo for inference. Additionally, for the parameter mismatch, you can check the parameter of the model config (between your config and the prediction config of the huggingface demo.

**Comment by zfbi** [comment]
I want to express my sincere appreciation for your work. I truly admire the effort you have put into it. Thank you so much for your assistance.
