### ISSUE TITLE
about Visualization

### ISSUE THREAD

**Issue by YananGu** [KyanChen/RSPrompter#22]
Hi, I run the python tools/predict.py,The program ran smoothly, but I didn't find the visualization result. How should I call out the result？ Thank you

**Comment by KyanChen** [comment]
check visualization config

**Comment by Z-MU-Z** [comment]
I only found $work_dir/visualizer/vis_data/config.py, so how to view the picture?

**Comment by xudongwang123** [comment]
Me too. I only found $work_dir/visualizer/vis_data/config.py

**Comment by KyanChen** [comment]
use [predict_rsprompter_anchor_nwpu.py](https://github.com/KyanChen/RSPrompter/blob/cky/configs/rsprompter/predict_rsprompter_anchor_nwpu.py) config file, and check DetVisualizationHook config parameters

**Comment by WanFeng123313** [comment]
![image](https://github.com/KyanChen/RSPrompter/assets/81793539/4267d4b8-8b14-412f-9bcd-d86da219391b)
我更改了训练使用的configs中py文件的callbacks，然后添加visualizer可以保存可视化图像，供参考
