### ISSUE TITLE
How to increase mIoU evaluation indicators?

### ISSUE THREAD

**Issue by tensornull** [KyanChen/RSPrompter#23]
First of all, thank you for your nice work.

I have two questions that I would like to ask you for advice.

1. I want to be try SAM-seg in Potsdam dataset(semantic segmentation dataset), What are the general implementation steps?
2. I hope to try to increase the statistics and evaluation results of mIoU and F1-Score. How should I modify the config file (taking samseg_mask2former_whu_config.py as an example) based on mmseg's iou_metric?

**Comment by KyanChen** [comment]
you can try fcn head for training
