### ISSUE TITLE
when it will be available on the mmdectetion? 

### ISSUE THREAD

**Issue by Jasper0068** [KyanChen/RSPrompter#27]
Hi keyan! 
I was very inspired by your work in the last mmlab talk when I heard that your work will soon be integrated into mmdectetion and support coco training! I would like to enquire about roughly when it will be available on the mmdectetion? 
Thanks again for your excellent work, and selfless open source! 
Best wishes!

**Comment by KyanChen** [comment]
in 1 weeks

**Comment by Jasper0068** [comment]
That's  great, thanks~
