### ISSUE TITLE
Integrate this algorithm into MMDet?

### ISSUE THREAD

**Issue by hhaAndroid** [KyanChen/RSPrompter#3]
Hello, this is very practical work. May I ask if you have the time or idea to integrate this algorithm into mmdet? We can provide the necessary assistance. Thank you.

**Comment by KyanChen** [comment]
No Problem. My Wechat is 13121205596
| |
陈科研
博士生
| |
|
北京航空航天大学
13121205596
***@***.***
北京市昌平区北京航空航天大学
|
---- Replied Message ----
| From | Haian ***@***.***> |
| Date | 07/03/2023 10:34 |
| To | KyanChen/RSPrompter ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [KyanChen/RSPrompter] Integrate this algorithm into MMDet? (Issue #3) |

Hello, this is very practical work. May I ask if you have the time or idea to integrate this algorithm into mmdet? We can provide the necessary assistance. Thank you.

**Comment by KyanChen** [comment]
ok, please contact me with kychen@buaa.edu.cn
