### ISSUE TITLE
The result is not the same with paper

### ISSUE THREAD

**Issue by wuwuwuxxx** [KyanChen/RSPrompter#31]
I use the pretrained weights u provided in huggingface and test it for NWPU val data. but i got the different result from the paper. 
Can you tell me what I might be doing wrong. Thank u for very much!
![image](https://github.com/KyanChen/RSPrompter/assets/13163233/a55f2e81-d6f6-4e0d-916e-c031b52c4c0e)

**Comment by KyanChen** [comment]
Maybe there is something wrong!
Here is a copy of the SAM-query under different config.
<img width="934" alt="image" src="https://github.com/KyanChen/RSPrompter/assets/41983514/e1139610-7b7a-4025-8a11-a965c7409490">

**Comment by wuwuwuxxx** [comment]
I test the SAM-anchor not the SAM-query. And I download the weights from https://huggingface.co/spaces/KyanChen/RSPrompter/tree/main/pretrain. And I download the data from this repo. 
The config file is downloaded from https://huggingface.co/spaces/KyanChen/RSPrompter/tree/main/configs/huggingface. 
Please tell me how can i get the right result same with the paper. Thank you very much!

**Comment by YananGu** [comment]
@wuwuwuxxx  Have you got the result same with the paper?
