### ISSUE TITLE
Why are my results all 0 during training?

### ISSUE THREAD

**Issue by Fairywyt** [KyanChen/RSPrompter#32]
![image](https://github.com/KyanChen/RSPrompter/assets/63852235/a202ce28-1154-4107-b355-7bb3d34a2505)

**Comment by KyanChen** [comment]
check your annotation

**Comment by Hannahzyt** [comment]
hello! I have a question that why the results in samseg_maskrcnn is correct but the results in rsprompter are all 0 with the same data, just like the above?

**Comment by pkyzh2006** [comment]
Hello, have you solved this issue? I used my own dataset, and have no problem using when using rsprompter, but both maskrcnn and samseg_maskrcnn shows that during training, the valsegm(0, 50, 75) is 0, while valbbox is fine.
