### ISSUE TITLE
train.py出现FileNotFoundError

### ISSUE THREAD

**Issue by winglucky** [KyanChen/RSPrompter#34]
您好！想请问一下运行train.py后出现的错误是找不到对应的数据源(如下图所示)，请问是直接在config文件里对data_prefix路径进行修改吗？以及为什么抓取的图像数据的名字是2_211.tif但在程序文件里却没看到有这个图像来源的提示？data_parent是对的。望回复，谢谢？
![image](https://github.com/KyanChen/RSPrompter/assets/134920598/3b390f40-7786-45b0-a16b-ea211cb7a122)
![image](https://github.com/KyanChen/RSPrompter/assets/134920598/36623724-aa8e-42ac-a324-e2ae58ff26da)

**Comment by KyanChen** [comment]
check the annotations
