### ISSUE TITLE
How to fine-tune the decoder of sam?

### ISSUE THREAD

**Issue by willpat1213** [KyanChen/RSPrompter#35]
Thanks to the author for such a good job.
I want to unfreeze the decoder of sam and fine-tune it when I follow this work, how can I do it？

**Comment by KyanChen** [comment]
You can add the name of decoder to sub_model_train = [
    'panoptic_head',
    'panoptic_fusion_head',
    'data_preprocessor'
]

**Comment by willpat1213** [comment]
Thank you for your answer, but you seem to have misunderstood what I mean, I need to unfreeze the decoder part of sam and add it to model training and parameter update instead of training maskformer_fusion_head.

**Comment by pkyzh2006** [comment]
I also want to implement this function. In the paper, the author states that testing has been conducted. How is it set up?

**Comment by willpat1213** [comment]
Here is my WeChat: -Layon, we can discuss about this.
