### ISSUE TITLE
数据集标签转换

### ISSUE THREAD

**Issue by WanFeng123313** [KyanChen/RSPrompter#38]
您好，作者，我看您用的NWPU和SSDD这两个数据集都是目标检测的标签，而您训练这两个数据集是用的json实例分割标签，请问您是怎么完成目标检测到实例分割标签的转换的？是重新标注还是用什么模型自动化生成的吗？期待您的回复。

**Comment by tensornull** [comment]
我猜的，NWPU和SSDD应该都是来自这里

https://github.com/chaozhong2010/VHR-10_dataset_coco

**Comment by WanFeng123313** [comment]
> 我猜的，NWPU和SSDD应该都是来自这里
> 
> https://github.com/chaozhong2010/VHR-10_dataset_coco

好的，非常感谢，我刚看了，使用labelme重新标注的。

**Comment by KyanChen** [comment]
对，文章中有说明
