### ISSUE TITLE
Could you provide your ckpt file conveniently?

### ISSUE THREAD

**Issue by Yanmoche** [KyanChen/RSPrompter#41]
Thank you very much for your project. I encountered such an error when running test.py. I learned that it is because I need to use the ckpt file I trained. Could you provide your ckpt file conveniently?

**Comment by Yanmoche** [comment]
![image](https://github.com/KyanChen/RSPrompter/assets/97887644/7fd7a86e-8bca-4809-9742-287b4aabfd6a)

**Comment by KyanChen** [comment]
You can add some key-value pairs to pth and save it as ckpt
