### ISSUE TITLE
query-base训练不收敛

### ISSUE THREAD

**Issue by an1018** [KyanChen/RSPrompter#44]
关于代码训练有2个疑问，非常希望得到解答，谢谢：
1）为什么使用WHU+query config，训练模型不收敛
![image](https://github.com/KyanChen/RSPrompter/assets/19808900/c6f803cf-c34d-47d3-9bf9-0a2f8ff3a9c2)

2）WHU + anchor config不能达到论文中的指标，请问还需要调整额外的参数吗
![image](https://github.com/KyanChen/RSPrompter/assets/19808900/ca548534-e7c6-4dbf-9bb0-2f8cd7336c12)

**Comment by KyanChen** [comment]
Try some augmentations. When I carry out experiments, I find more epochs perform better. Also, different trials will get very different results. You can try resume from the ckpt and conduct different trials. You can also change the selected_channels and prompt_shape parameters.

**Comment by an1018** [comment]
1）The query-based method has run 2000 epochs and is still 0

2）anchor-base：
I see only horizontal flip enhancement in your paper. And can't get the same  mAP whit default rsprompter_anhor_whu_config.py 
![image](https://github.com/KyanChen/RSPrompter/assets/19808900/edc21f31-b2c4-46a9-960d-3817f1088e5e)

**Comment by YananGu** [comment]
@an1018 我跑NWPU也得不到论文里的结果，你用tool/test.py 测checkpoint了吗，训练结束后我测出来的结果和训练时候不一致。。

**Comment by an1018** [comment]
是的，test.py更低

**Comment by YananGu** [comment]
我跑query也全是零
