### ISSUE TITLE
阅读论文关于提示生成的疑问？

### ISSUE THREAD

**Issue by ZHIZIHUABU** [KyanChen/RSPrompter#46]
论文中提到了基于anchor和query生成的提示；
1、基于anchor类似于sam-det，是用监督训练得到的边界框的坐标和类别生成提示，对于较难分割的物体仅提供box可能无法达到较好的分割效果；
2、基于query生成的提示我不太理解，请问是使用mlp-prompt生成提示点吗？这样生成的点坐标越多理论上是越准确的，但是生成的提示点无法使用标签对其训练，所以直接对提示点最终生成的mask与gt_label进行训练，这样理解对吗，好像无法对提示点进行回归训练模型不太好收敛？
我觉得第2种方法似乎是更准确的，我在使用SAM时只要提示点足够多，总能达到一个较好的分割效果。

**Comment by KyanChen** [comment]
2、生成的不是点提示，而是嵌入特征
