### ISSUE TITLE
Predict.py file running error

### ISSUE THREAD

**Issue by pkyzh2006** [KyanChen/RSPrompter#47]
vit-b and vit-h training both completed successfully. However, when running predictions, vit-b predicts normally while vit-h throws an error：

RuntimeError: Error(s) in loading state_dict for SegSAMAnchorPLer:
	Missing key(s) in state_dict: "panoptic_head.neck.down_sample_layers.12.0.conv.weight", "panoptic_head.neck.down_sample_layers.12.0.bn.weight", "panoptic_head.neck.down_sample_layers.12.0.bn.bias", "panoptic_head.neck.down_sample_layers.12.0.bn.running_mean", "panoptic_head.neck.down_sample_layers.12.0.bn.running_var", "panoptic_head.neck.down_sample_layers.12.1.conv.weight", "panoptic_head.neck.down_sample_layers.12.1.bn.weight", "panoptic_head.neck.down_sample_layers.12.1.bn.bias", "panoptic_head.neck.down_sample_layers.12.1.bn.running_mean", "panoptic_head.neck.down_sample_layers.12.1.bn.running_var", "panoptic_head.neck.down_sample_layers.13.0.conv.weight", "panoptic_head.neck.down_sample_layers.13.0.bn.weight", "panoptic_head.neck.down_sample_layers.13.0.bn.bias", "panoptic_head.neck.down_sample_layers.13.0.bn.running_mean", "panoptic_head.neck.down_sample_layers.13.0.bn.running_var", "panoptic_head.neck.down_sample_layers.13.1.conv.weight", "panoptic_head.neck.down_sample_layers.13.1.bn.weight", "panoptic_head.neck.down_sample_layers.13.1.bn.bias", "panoptic_head.neck.down_sample_layers.13.1.bn.running_mean", "panoptic_head.neck.down_sample_layers.13.1.bn.running_var", "panoptic_head.neck.fusion_layers.12.conv.weight", "panoptic_head.neck.fusion_layers.12.bn.weight", "panoptic_head.neck.fusion_layers.12.bn.bias", "panoptic_head.neck.fusion_layers.12.bn.running_mean", "panoptic_head.neck.fusion_layers.12.bn.running_var", "panoptic_head.neck.fusion_layers.13.conv.weight", "panoptic_head.neck.fusion_layers.13.bn.weight", "panoptic_head.neck.fusion_layers.13.bn.bias", "panoptic_head.neck.fusion_layers.13.bn.running_mean", "panoptic_head.neck.fusion_layers.13.bn.running_var". 

Is there something I missed when switching from vit-b to vit-h for predictions, with changes only in type, checkpoint, in_channels, and selected_channels, just like during training?

**Comment by KyanChen** [comment]
see the released new version!
