### ISSUE TITLE
你们的pth文件都保存在哪里？？？

### ISSUE THREAD

**Issue by jxhoh** [KyanChen/RSPrompter#49]
训练了好久，发现才4个epoch，你们的权重多久保存一次，都在哪设置的啊

**Comment by pkyzh2006** [comment]
配置文件上有写，保存三个最好的，以及last。所以是四个

**Comment by jxhoh** [comment]
我看到了，哈哈，原来是大模型训练太慢了，我说怎么两天了还没保存，它设了8个epoch保存一次

**Comment by KyanChen** [comment]
我们近期会优化一下输入图像的大小，让训练速度更快一些
