### ISSUE TITLE
Hello. Thanks for your wonderful work. Question about detection model

### ISSUE THREAD

**Issue by baibizhe** [KyanChen/RSPrompter#5]
Hello .Thanks for your wonderful work. 
I noticed that you trained an additional object detection model  in SAM-det. Have you ever considered embed an detection head after the SAM's image encoder ? Because (1) we could use the information from SAM's image encoder instead of training an image encoder from scratch (2) save some computational resources.

Best regards,
Bizhe

**Comment by KyanChen** [comment]
It also works. SAM-seg is what you mean to some extent. But SAM-seg is an implement of instance detection. It can also be replaced with a detection head to perform as an absolute object detection method. In addition, your analysis is also very correct. We also discussed the resource consumption of SAM decoder in the discussion section. To some extent, replacing the head is also an effective alternative.

**Comment by KyanChen** [comment]
Hope that other researchers can investigate a foundation model similar to SAM by replacing the head and combining adapter technology.

**Comment by KyanChen** [comment]
Thank you!

**Comment by baibizhe** [comment]
I am doing box prompt for SAM as well(But not in GEO , and additional module is embedded). 

Do you consider   collaborating  with SAM-det  part  with directly embedding an detection head  after SAM- encoder ?

**Comment by KyanChen** [comment]
I think it would like the architecture of  RSPromter-anchor

**Comment by baibizhe** [comment]
Yes! Thanks for your help .
