### ISSUE TITLE
你们都是怎么做预测的

### ISSUE THREAD

**Issue by jxhoh** [KyanChen/RSPrompter#51]
没找到预测，输出的位置，感觉很奇怪，好像没 --out

**Comment by wb315** [comment]
> 没找到预测，输出的位置，感觉很奇怪，好像没 --out

@jxhoh 作者预测没画结果图。。。我写了个简单的prdict脚本你参考下


```
import cv2
import torch
import os
import glob
import mmcv
import mmengine
import numpy as np
from mmengine import Config, get
from mmengine.dataset import Compose
from mmpl.registry import MODELS, VISUALIZERS
from mmpl.utils import register_all_modules
register_all_modules()

device = 'cuda:3' if torch.cuda.is_available() else 'cpu'


def construct_sample(img, pipeline):
   img = np.array(img)[:, :, ::-1]
   inputs = {
      'ori_shape': img.shape[:2],
      'img': img,
   }
   pipeline = Compose(pipeline)
   sample = pipeline(inputs)
   return sample


def build_model(cp, model_cfg):
   model_cpkt = torch.load(cp, map_location='cpu')
   model = MODELS.build(model_cfg)
   model.load_state_dict(model_cpkt["state_dict"], strict=True)
   model.to(device=device)
   model.eval()
   return model


def inference_func(ori_img, model, cfg, img_name):

   predict_pipeline = [
      dict(type='mmdet.Resize', scale=(1024, 1024)),
      dict(
         type='mmdet.PackDetInputs',
         meta_keys=('ori_shape', 'img_shape', 'scale_factor'))
   ]

   sample = construct_sample(ori_img, predict_pipeline)
   sample['inputs'] = [sample['inputs']]
   sample['data_samples'] = [sample['data_samples']]

   with torch.no_grad():
      pred_results = model.predict_step(sample, batch_idx=0)

   cfg.visualizer.setdefault('save_dir', 'visualizer')
   visualizer = VISUALIZERS.build(cfg.visualizer)

   data_sample = pred_results[0]
   img = np.array(ori_img).copy()
   out_file = f'visualizer/{img_name}'
   print(out_file)
   mmengine.mkdir_or_exist(os.path.dirname(out_file))

   visualizer.add_datasample(
      'test_img',
      img,
      draw_gt=False,
      data_sample=data_sample,
      show=False,
      wait_time=0.01,
      pred_score_thr=0.1,
      out_file=out_file
   )
   img_bytes = get(out_file)
   img = mmcv.imfrombytes(img_bytes, channel_order='rgb')
   return img


checkpoint = 'results/ssdd_ins/E20230629_2/checkpoints/epoch_epoch=549-map_valsegm_map_0=0.8961.ckpt'
cfg = 'configs/rsprompter/rsprompter_anchor_ssdd_config.py'
cfg = Config.fromfile(cfg)

model = build_model(checkpoint, cfg.model_cfg)

img_dir = ""
for img_name in os.listdir(img_dir):
   img = cv2.imread(os.path.join(img_dir, img_name))
   dst_img = inference_func(img, model, cfg, img_name)
```

**Comment by wb315** [comment]
@jxhoh

**Comment by jxhoh** [comment]
我现在，用主干网络，加了另外一个检测头，损失一直只能降到0.3，就很奇怪
有什么策略吗

**Comment by Xinghanzzy** [comment]
我也没找到输出的位置 
还有 这个代码读起来好累 有推荐的阅读思路吗

**Comment by l-cr** [comment]
@wb315 请问这个怎么整呀？
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by xiaohan2** [comment]
@wb315 您的代码会出现这个错误，KeyError: 'visualizer'；请问时需要修改什么配置吗

**Comment by Zhouzia** [comment]
> @wb315 您的代码会出现这个错误，KeyError: 'visualizer'；请问时需要修改什么配置吗
在configs\rsprompter文件夹的文件里只有predict_rsprompter_anchor_nwpu.py里是有visualizer属性的，其他作者都没加上去，可以参考predict_rsprompter_anchor_nwpu.py，给你使用的配置文件加上。
`vis_backends = [dict(type='mmdet.LocalVisBackend')]
visualizer = dict(
    type='mmdet.DetLocalVisualizer',
    vis_backends=vis_backends,
    name='visualizer',
    fig_save_cfg=dict(
        frameon=True,
        figsize=(40, 20),
        # dpi=300,
    ),
    line_width=2,
    alpha=0.8
)`
就可以了

**Comment by KyanChen** [comment]
最近基于mmdetecton发布了新版本，可以了解一下

**Comment by moderate-leon** [comment]
> > 没找到预测，输出的位置，感觉很奇怪，好像没 --out
> 
> @jxhoh 作者预测没画结果图。。。我写了个简单的prdict脚本你参考下
> 
> ```
> import cv2
> import torch
> import os
> import glob
> import mmcv
> import mmengine
> import numpy as np
> from mmengine import Config, get
> from mmengine.dataset import Compose
> from mmpl.registry import MODELS, VISUALIZERS
> from mmpl.utils import register_all_modules
> register_all_modules()
> 
> device = 'cuda:3' if torch.cuda.is_available() else 'cpu'
> 
> 
> def construct_sample(img, pipeline):
>    img = np.array(img)[:, :, ::-1]
>    inputs = {
>       'ori_shape': img.shape[:2],
>       'img': img,
>    }
>    pipeline = Compose(pipeline)
>    sample = pipeline(inputs)
>    return sample
> 
> 
> def build_model(cp, model_cfg):
>    model_cpkt = torch.load(cp, map_location='cpu')
>    model = MODELS.build(model_cfg)
>    model.load_state_dict(model_cpkt["state_dict"], strict=True)
>    model.to(device=device)
>    model.eval()
>    return model
> 
> 
> def inference_func(ori_img, model, cfg, img_name):
> 
>    predict_pipeline = [
>       dict(type='mmdet.Resize', scale=(1024, 1024)),
>       dict(
>          type='mmdet.PackDetInputs',
>          meta_keys=('ori_shape', 'img_shape', 'scale_factor'))
>    ]
> 
>    sample = construct_sample(ori_img, predict_pipeline)
>    sample['inputs'] = [sample['inputs']]
>    sample['data_samples'] = [sample['data_samples']]
> 
>    with torch.no_grad():
>       pred_results = model.predict_step(sample, batch_idx=0)
> 
>    cfg.visualizer.setdefault('save_dir', 'visualizer')
>    visualizer = VISUALIZERS.build(cfg.visualizer)
> 
>    data_sample = pred_results[0]
>    img = np.array(ori_img).copy()
>    out_file = f'visualizer/{img_name}'
>    print(out_file)
>    mmengine.mkdir_or_exist(os.path.dirname(out_file))
> 
>    visualizer.add_datasample(
>       'test_img',
>       img,
>       draw_gt=False,
>       data_sample=data_sample,
>       show=False,
>       wait_time=0.01,
>       pred_score_thr=0.1,
>       out_file=out_file
>    )
>    img_bytes = get(out_file)
>    img = mmcv.imfrombytes(img_bytes, channel_order='rgb')
>    return img
> 
> 
> checkpoint = 'results/ssdd_ins/E20230629_2/checkpoints/epoch_epoch=549-map_valsegm_map_0=0.8961.ckpt'
> cfg = 'configs/rsprompter/rsprompter_anchor_ssdd_config.py'
> cfg = Config.fromfile(cfg)
> 
> model = build_model(checkpoint, cfg.model_cfg)
> 
> img_dir = ""
> for img_name in os.listdir(img_dir):
>    img = cv2.imread(os.path.join(img_dir, img_name))
>    dst_img = inference_func(img, model, cfg, img_name)
> ```



> > 没找到预测，输出的位置，感觉很奇怪，好像没 --out
> 
> @jxhoh 作者预测没画结果图。。。我写了个简单的prdict脚本你参考下
> 
> ```
> import cv2
> import torch
> import os
> import glob
> import mmcv
> import mmengine
> import numpy as np
> from mmengine import Config, get
> from mmengine.dataset import Compose
> from mmpl.registry import MODELS, VISUALIZERS
> from mmpl.utils import register_all_modules
> register_all_modules()
> 
> device = 'cuda:3' if torch.cuda.is_available() else 'cpu'
> 
> 
> def construct_sample(img, pipeline):
>    img = np.array(img)[:, :, ::-1]
>    inputs = {
>       'ori_shape': img.shape[:2],
>       'img': img,
>    }
>    pipeline = Compose(pipeline)
>    sample = pipeline(inputs)
>    return sample
> 
> 
> def build_model(cp, model_cfg):
>    model_cpkt = torch.load(cp, map_location='cpu')
>    model = MODELS.build(model_cfg)
>    model.load_state_dict(model_cpkt["state_dict"], strict=True)
>    model.to(device=device)
>    model.eval()
>    return model
> 
> 
> def inference_func(ori_img, model, cfg, img_name):
> 
>    predict_pipeline = [
>       dict(type='mmdet.Resize', scale=(1024, 1024)),
>       dict(
>          type='mmdet.PackDetInputs',
>          meta_keys=('ori_shape', 'img_shape', 'scale_factor'))
>    ]
> 
>    sample = construct_sample(ori_img, predict_pipeline)
>    sample['inputs'] = [sample['inputs']]
>    sample['data_samples'] = [sample['data_samples']]
> 
>    with torch.no_grad():
>       pred_results = model.predict_step(sample, batch_idx=0)
> 
>    cfg.visualizer.setdefault('save_dir', 'visualizer')
>    visualizer = VISUALIZERS.build(cfg.visualizer)
> 
>    data_sample = pred_results[0]
>    img = np.array(ori_img).copy()
>    out_file = f'visualizer/{img_name}'
>    print(out_file)
>    mmengine.mkdir_or_exist(os.path.dirname(out_file))
> 
>    visualizer.add_datasample(
>       'test_img',
>       img,
>       draw_gt=False,
>       data_sample=data_sample,
>       show=False,
>       wait_time=0.01,
>       pred_score_thr=0.1,
>       out_file=out_file
>    )
>    img_bytes = get(out_file)
>    img = mmcv.imfrombytes(img_bytes, channel_order='rgb')
>    return img
> 
> 
> checkpoint = 'results/ssdd_ins/E20230629_2/checkpoints/epoch_epoch=549-map_valsegm_map_0=0.8961.ckpt'
> cfg = 'configs/rsprompter/rsprompter_anchor_ssdd_config.py'
> cfg = Config.fromfile(cfg)
> 
> model = build_model(checkpoint, cfg.model_cfg)
> 
> img_dir = ""
> for img_name in os.listdir(img_dir):
>    img = cv2.imread(os.path.join(img_dir, img_name))
>    dst_img = inference_func(img, model, cfg, img_name)
> ```

大佬，我用这个代码输出的图像中怎么没有预测结果啊，不报错，输出的图像都是原图，没有预测框和分割边界，是哪里有问题吗？
![609](https://github.com/KyanChen/RSPrompter/assets/107356344/1ddac8f6-e452-4fcd-87a4-c9bac93525da)

**Comment by moderate-leon** [comment]
> > @wb315 您的代码会出现这个错误，KeyError: 'visualizer'；请问时需要修改什么配置吗
> > 在configs\rsprompter文件夹的文件里只有predict_rsprompter_anchor_nwpu.py里是有visualizer属性的，其他作者都没加上去，可以参考predict_rsprompter_anchor_nwpu.py，给你使用的配置文件加上。
> > 
> > 就可以了`vis_backends = [dict(type='mmdet.LocalVisBackend')] visualizer = dict(     type='mmdet.DetLocalVisualizer',     vis_backends=vis_backends,     name='visualizer',     fig_save_cfg=dict(         frameon=True,         figsize=(40, 20),         # dpi=300,     ),     line_width=2,     alpha=0.8 )`

你运行得到的预测图片中有预测结果吗？（预测框和分割边界，我运行得到的测试图像上面什么都没有啊）

**Comment by w243943** [comment]
> > > [@wb315](https://github.com/wb315) 您的代码会出现这个错误，KeyError: 'visualizer'；请问时需要修改什么配置吗
> > > 在configs\rsprompter文件夹的文件里只有predict_rsprompter_anchor_nwpu.py里是有visualizer属性的，其他作者都没加上去，可以参考predict_rsprompter_anchor_nwpu.py，给你使用的配置文件加上。
> > > 就可以了`vis_backends = [dict(type='mmdet.LocalVisBackend')] visualizer = dict(     type='mmdet.DetLocalVisualizer',     vis_backends=vis_backends,     name='visualizer',     fig_save_cfg=dict(         frameon=True,         figsize=(40, 20),         # dpi=300,     ),     line_width=2,     alpha=0.8 )`
> 
> 你运行得到的预测图片中有预测结果吗？（预测框和分割边界，我运行得到的测试图像上面什么都没有啊）

你可以查看一下你的dataset中定义是否出现了你的数据集中的类的名字，如果在训练的时候只有cls的损失，但是没有mask和dice损失可能会是这个问题
