### ISSUE TITLE
Does mask_decoder in RSPrompter participate in training?

### ISSUE THREAD

**Issue by willpat1213** [KyanChen/RSPrompter#55]
The paper states that `mask_decoder` is frozen, but I see that `mask_decoder` is written in `panoptic_head` in the code, and `sub_model_train` also includes `panoptic_head`. Does this mean that `mask_decoder` will participate in training? If it does not participate in training, how should I modify the code to participate in training?

**Comment by KyanChen** [comment]
The decoder in the latest version has been included in the training phase.
