### ISSUE TITLE
How to change the input image size?

### ISSUE THREAD

**Issue by pengyuting181** [KyanChen/RSPrompter#56]
Can we modify the size of the input image?
![2NG@ E}1Z71R4GIUK1}2%09](https://github.com/KyanChen/RSPrompter/assets/145330123/6de2737c-2dd0-4c43-8684-6a0e375fdced)
The encoder model seems to be frozen, so is the image size modifiable？Or is it fixed？

**Comment by lanfeiwuwudibang** [comment]
啊，我也是不知道咋改

**Comment by KyanChen** [comment]
Please stand by. We will make it work soon!
