### ISSUE TITLE
使用NWPU数据集，训练过程中loss值正常，验证时精度一直为0。

### ISSUE THREAD

**Issue by moderate-leon** [KyanChen/RSPrompter#57]
没有改动Config文件中除了数据路径外其他内容，有人遇到这种情况吗？
训练信息：Epoch 3:  73%|▋| 190/260 [03:49<01:24,  1.21s/it, v_num=1age, train_loss=33.20, train_loss_cls=2.570, train_loss_mask=0.947, train_loss_dice=4.840, train_d0.loss_cls=2.510, train_d0.loss_mask=0.964,
评估出现问题：
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.03s).
Accumulating evaluation results...
DONE (t=0.01s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
segm_mAP_copypaste: 0.000 0.000 0.000 -1.000 0.000 -1.000

**Comment by King-king424** [comment]
loss怎么这么大

**Comment by shhjjj** [comment]
我也是这样的，请问你解决这个了吗

**Comment by moderate-leon** [comment]
> loss怎么这么大

loss波动大，可能刚好我截出来的时候碰巧比较大

**Comment by moderate-leon** [comment]
> 我也是这样的，请问你解决这个了吗

我前些天一直在找是不是数据读取什么的出了问题，结果我发现不是咱们的问题。query的方法作者训了5000个epoch，训练几百个epoch后精度就不是零了。anchor的收敛更快一些，40个epoch左右验证精度就不为零了。主要是训练太慢了，我bs只能设为2，一天只能run 100个epoch。

**Comment by KyanChen** [comment]
我们基于mmdetection提供了新版本，收敛更快一些。近期我们也会增加一些策略，让显存占用更低，速度更快

**Comment by moderate-leon** [comment]
大佬，什么时候在mmdetection上线啊，还是说现在在mmdetection开发版中已经有了



---原始邮件---
发件人: "Keyan ***@***.***&gt;
发送时间: 2023年11月25日(周六) 晚上11:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [KyanChen/RSPrompter] 使用NWPU数据集，训练过程中loss值正常，验证时精度一直为0。 (Issue #57)




 
我们基于mmdetection提供了新版本，收敛更快一些。近期我们也会增加一些策略，让显存占用更低，速度更快
