### ISSUE TITLE
Ask for demo

### ISSUE THREAD

**Issue by Zdong104** [KyanChen/RSPrompter#6]
Hi, I am try to use your work in droplet segmentation, can you put a demo about how to use it please, I saw you mentioned 

"you need to configure the test_evaluator and test_loader in the configuration file, as well as the config and ckpt-path paths in tools/test.py, and then run"

if that is possible to use Google Colab as a demo please, for example, my folder is called 'conten/drive/MyDrive/RSPrompter' and my images set is saved as 'conten/drive/MyDrive/image.npz' or folder conten/drive/MyDrive/images' model is saved in the folder 'conten/drive/MyDrive/RSPrompter/models'. can you provide more details about which file I need to change or which line I need to change.

**Comment by KyanChen** [comment]
You can try the hugging face demo, and see how it inference!

**Comment by Zdong104** [comment]
Thank you for informing me that issue #6 has been closed. I appreciate your
prompt action and attention to this matter.

Please let me know if there is anything else I can assist you with.

Best regards,
Z Dong
