### ISSUE TITLE
KeyError: 'pytorch-lightning_version'

### ISSUE THREAD

**Issue by bugcat9** [KyanChen/RSPrompter#62]
我想直接进行`python tools/test.py`验证一下，但是报了KeyError: 'pytorch-lightning_version'，错误如下：
```
  File "/home/yy448/ProgramFiles/anaconda3/envs/RSPrompter/lib/python3.10/site-packages/lightning/pytorch/utilities/migration/utils.py", line 136, in _get_version
    return checkpoint["pytorch-lightning_version"]
KeyError: 'pytorch-lightning_version'
```
因为之前使用pytorch较多，这个pytorch-lightning不清楚怎么进行添加，希望大佬指点一下方向

**Comment by Kevinorve** [comment]
I think is the version of pytorch-lightning dismatch with some other packages,I also found this problem.And even if I changed the envs code and added the key "pytorch-lightning_version" into the checkpoint, it still has other key missed, such as "global_step".

**Comment by Kevinorve** [comment]
change tools/test.py like this:
    if 'runner_type' not in cfg:
        runner = PLRunner.from_cfg(cfg)
        runner.model.load_state_dict(torch.load(args.ckpt_path))
    else:
        runner = RUNNERS.build(cfg)
    runner.run(args.status)
at around line 34 - 40
this will work, you need to import torch at the head of this file

**Comment by DianSymerry** [comment]
你直接copy源文件跑predict是行不通的。predict需要你在原有的训练基础上指定ckpt才可以工作。

**Comment by bugcat9** [comment]
> 你直接copy源文件跑predict是行不通的。predict需要你在原有的训练基础上指定ckpt才可以工作。

我下载了RSPrompter-anchor的模型，然后在cfg里面指向这个模型，但是也使用这个模型没有运行成功

**Comment by KyanChen** [comment]
可以尝试下新版本，模型权重马上会上传

**Comment by lr-dddd** [comment]
> 我想直接进行`python tools/test.py`验证一下，但是报了KeyError: 'pytorch-lightning_version'，错误如下：
> 
> ```
>   File "/home/yy448/ProgramFiles/anaconda3/envs/RSPrompter/lib/python3.10/site-packages/lightning/pytorch/utilities/migration/utils.py", line 136, in _get_version
>     return checkpoint["pytorch-lightning_version"]
> KeyError: 'pytorch-lightning_version'
> ```
> 
> 因为之前使用pytorch较多，这个pytorch-lightning不清楚怎么进行添加，希望大佬指点一下方向

我下载了huggingface的模型，也还是会出现这个问题欸
