### ISSUE TITLE
Why do you need to train so many rounds?

### ISSUE THREAD

**Issue by King-king424** [KyanChen/RSPrompter#63]
Whether it's anchor-based or query-based, there are too many training rounds. I wonder if other remote sensing instance segmentation methods also require so many rounds of training? Or is the method proposed in this article converge too slowly, so that it requires so many rounds of training.

**Comment by King-king424** [comment]
Are there any performance results for intermediate epochs? For example, 50, 100, 150, 200.

**Comment by DianSymerry** [comment]
i am also amazed for the training rounds.

**Comment by Daisygotit666** [comment]
> Whether it's anchor-based or query-based, there are too many training rounds. I wonder if other remote sensing instance segmentation methods also require so many rounds of training? Or is the method proposed in this article converge too slowly, so that it requires so many rounds of training.
I wonder why 100 epochs is too many for you

**Comment by lanfeiwuwudibang** [comment]
我是高分影像，设置2000轮，batch_size4，img_size512,跑了一个月才650轮这样，最主要是我的验证咋感觉很奇怪（654epoch:segm_mAP_copypaste:0.1,0.5,0.000, 0.000, -1.000,0.200），我做了test验证，报错没有分割器没有test_evaluator，predict不报错，有进度条，但是咋只保存了log结果，啥也没有捏，不清楚是训练模型轮数不够还是数据有问题，我也检查了数据   跟作者的数据的格式是一样的，可视化也没有问题，配置文件参数也没有瞎改，就一些很基本的，好想知道我的问题在哪里

**Comment by KyanChen** [comment]
A new version has been released, and the coverage is faster!
