### ISSUE TITLE
size dismatch error when using weights NWPU_anchor.pth 

### ISSUE THREAD

**Issue by Kevinorve** [KyanChen/RSPrompter#64]
Traceback (most recent call last):
  File "/home/user/xy/RSPrompter-cky/tools/test.py", line 45, in <module>
    main()
  File "/home/user/xy/RSPrompter-cky/tools/test.py", line 37, in main
    runner.model.load_state_dict(torch.load(args.ckpt_path))    # added
  File "/home/user/anaconda3/envs/RSPro/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SegSAMAnchorPLer:
        Unexpected key(s) in state_dict: "panoptic_head.neck.down_sample_layers.12.0.conv.weight", "panoptic_head.neck.down_sample_layers.12.0.bn.weight", "panoptic_head.neck.down_sample_layers.12.0.bn.bias", "panoptic_head.neck.down_sample_layers.12.0.bn.running_mean", "panoptic_head.neck.down_sample_layers.12.0.bn.running_var", "panoptic_head.neck.down_sample_layers.12.0.bn.num_batches_tracked", "panoptic_head.neck.down_sample_layers.12.1.conv.weight", "panoptic_head.neck.down_sample_layers.12.1.bn.weight", "panoptic_head.neck.down_sample_layers.12.1.bn.bias", "panoptic_head.neck.down_sample_layers.12.1.bn.running_mean", "panoptic_head.neck.down_sample_layers.12.1.bn.running_var", "panoptic_head.neck.down_sample_layers.12.1.bn.num_batches_tracked", "panoptic_head.neck.down_sample_layers.13.0.conv.weight", "panoptic_head.neck.down_sample_layers.13.0.bn.weight", "panoptic_head.neck.down_sample_layers.13.0.bn.bias", "panoptic_head.neck.down_sample_layers.13.0.bn.running_mean", "panoptic_head.neck.down_sample_layers.13.0.bn.running_var", "panoptic_head.neck.down_sample_layers.13.0.bn.num_batches_tracked", "panoptic_head.neck.down_sample_layers.13.1.conv.weight", "panoptic_head.neck.down_sample_layers.13.1.bn.weight", "panoptic_head.neck.down_sample_layers.13.1.bn.bias", "panoptic_head.neck.down_sample_layers.13.1.bn.running_mean", "panoptic_head.neck.down_sample_layers.13.1.bn.running_var", "panoptic_head.neck.down_sample_layers.13.1.bn.num_batches_tracked", "panoptic_head.neck.fusion_layers.12.conv.weight", "panoptic_head.neck.fusion_layers.12.bn.weight", "panoptic_head.neck.fusion_layers.12.bn.bias", "panoptic_head.neck.fusion_layers.12.bn.running_mean", "panoptic_head.neck.fusion_layers.12.bn.running_var", "panoptic_head.neck.fusion_layers.12.bn.num_batches_tracked", "panoptic_head.neck.fusion_layers.13.conv.weight", "panoptic_head.neck.fusion_layers.13.bn.weight", "panoptic_head.neck.fusion_layers.13.bn.bias", "panoptic_head.neck.fusion_layers.13.bn.running_mean", "panoptic_head.neck.fusion_layers.13.bn.running_var", "panoptic_head.neck.fusion_layers.13.bn.num_batches_tracked". 
        size mismatch for panoptic_head.roi_head.mask_head.point_emb.8.weight: copying a param with shape torch.Size([2560, 256]) from checkpoint, the shape in current model is torch.Size([2048, 256]).
        size mismatch for panoptic_head.roi_head.mask_head.point_emb.8.bias: copying a param with shape torch.Size([2560]) from checkpoint, the shape in current model is torch.Size([2048]).

Encountered bug above when using command 
python tools/test.py --config configs/rsprompter/rsprompter_anchor_nwpu_config.py --ckpt-path pretrain/NWPU_anchor.pth.
To avoid the error  'KeyError: 'pytorch-lightning_version' ', I changed the weights load code in tools/test.py like this:
    if 'runner_type' not in cfg:     # line 34
        runner = PLRunner.from_cfg(cfg)
        runner.model.load_state_dict(torch.load(args.ckpt_path))    # added
    else:
        runner = RUNNERS.build(cfg)
    runner.run(args.status)
    # runner.run(args.status, ckpt_path=args.ckpt_path)  # former

Did I missed something or did something wrong?

**Comment by chemscher** [comment]
If  you are using the `configs/rsprompter/rsprompter_anchor_nwpu_config.py`, I just changed this file as below:
1. `prompt_shape=(60,5)` 
2. `selected_channels=range(4, 32, 2)` in `panoptic_head.neck`
and it worked. 

@Kevinorve

**Comment by KyanChen** [comment]
We have released a new version, and upload ckpt soon.
