### ISSUE TITLE
为什么同样使用同一个虚拟环境，我一直报这个错误，IndexError: list index out of range，求解，谢谢

### ISSUE THREAD

**Issue by gangtieyang** [KyanChen/RSPrompter#65]
IndexError: list index out of range

**Comment by DianSymerry** [comment]
i also met the same error when using other seg dataset.
the train.py stopped working at this point:
Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]
......
  File "F:\RSPrompter-cky\tools/..\mmpl\models\necks\sam_prompt_generator.py", line 956, in <listcomp>
    inner_states = [einops.rearrange(inner_states[idx], 'b h w c -> b c h w') for idx in self.selected_channels]
IndexError: list index out of range

**Comment by zlsisgod** [comment]
i also met the same error when using other seg dataset. @DianSymerry have you solved this error?

**Comment by zlsisgod** [comment]
I have identified the problem. I am using the sam_vit_b weights, and this model's encoder only has 12 layers. However, the project extracts features from the 32 layers of the sam_vit_h type encoder.

**Comment by DianSymerry** [comment]
> I have identified the problem. I am using the sam_vit_b weights, and this model's encoder only has 12 layers. However, the project extracts features from the 32 layers of the sam_vit_h type encoder.

you are right.
it can be edited in the config files for different models. the author also makes a code comment here. for instance:
            # in_channels=[1280] * 32,
            in_channels=[768] * 12,
            inner_channels=32,
            # selected_channels=range(4, 32, 2),
            selected_channels=range(4, 12, 2),

**Comment by KyanChen** [comment]
You can try our new version now
