### ISSUE TITLE
Thanks for your wonderful work. Question about  PE in Anchor-based Prompter

### ISSUE THREAD

**Issue by baibizhe** [KyanChen/RSPrompter#7]
Hello thanks for your wonderful work.
I noticed that you mentioned  "Since the Φroi-p operations may cause the subsequent prompt generation to lose positional information relative to the entire image, we incorporate positional encoding (PE) into the original fused features (Fagg)".
Would you mind pointing which part of the code implement this function?

**Comment by KyanChen** [comment]
[SinePositionalEncoding](https://github.com/KyanChen/RSPrompter/blob/cky/mmpl/models/necks/sam_prompt_generator.py)

in Line 664: `self.generator_pe = SinePositionalEncoding(**positional_encoding)`

**Comment by baibizhe** [comment]
Thanks
