### ISSUE TITLE
Cannot find ‘RSPrompterQuery’

### ISSUE THREAD

**Issue by pkyzh2006** [KyanChen/RSPrompter#72]
Thank you for your wonderful job. In the latest version that I tested, there are the following issues：

I tried query-based one, and I got

KeyError: 'RSPrompterQuery is not in the mmdet::model registry. Please check whether the value of `RSPrompterQuery` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

This "RSPrompterQuery" was indeed not found in the code.  Thank you in advance. I'd appreciate it if you could take a look at this issue.

**Comment by KyanChen** [comment]
fixed
