### ISSUE TITLE
Compare the time spent for each epoch between the latest version and the original one

### ISSUE THREAD

**Issue by pkyzh2006** [KyanChen/RSPrompter#73]
Hi there, I'm experimenting with a query-based method using my own dataset, which consists of around 2000 images, each containing no more than 3 instances usually. I have access to a single GPU with 40GB RAM. Therefore, at the moment and I haven't enabled AMP.

In the original version, it takes approximately 6 mins for each epoch, and I'm able to train with a batch size of 6. Typically, it starts showing signs of overfitting after around 300 epochs (total epochs I set is 500). However, with the current version, each epoch takes around 30 minutes, and I can only set batch size with 1 due to limitation of RAM.

The training is still ongoing, and it seems it might take several days to complete. I'd like to inquire: in your tests, is it normal for each epoch to take significantly longer in the new version? Additionally, regarding the LR values specified in the config file, are they meant for a single GPU or for 8 GPUs?

**Comment by KyanChen** [comment]
The latest  version  has some updates, including multi-scale training, training with decoder, etc. We will update the newest version of paper soon. You can try deepspeed, modify the prompt shape for 3 if each image has only 3 instance, try other methods, try a smaller input shape, etc to speed up!

**Comment by pkyzh2006** [comment]
Additionally, I'm also curious about the potential improvement after adding Lora. Have you tested it yourself？ In the previous version, I conducted tests with my own dataset, comparing the performance between freezing and unfreezing the decoder section. The results is same with your paper.

**Comment by KyanChen** [comment]
The LoRA will not been included in our paper, and I wonder it will work well. I just implement it for efficient application. More experiments and improvement will be validated soon.

**Comment by pkyzh2006** [comment]
> The latest version has some updates, including multi-scale training, training with decoder, etc. We will update the newest version of paper soon. You can try deepspeed, modify the prompt shape for 3 if each image has only 3 instance, try other methods, try a smaller input shape, etc to speed up!

Thank you for your reply! I did modify the prompt shape, and keep the most of parameters consistent with the previous version. Thank you very much. I'll wait for your updating papers.

**Comment by pkyzh2006** [comment]
> The LoRA will not been included in our paper, and I wonder it will work well. I just implement it for efficient application. More experiments and improvement will be validated soon.

I hope so too. It should be effective.
