### ISSUE TITLE
inference on custom dataset 

### ISSUE THREAD

**Issue by 15926273249** [KyanChen/RSPrompter#74]
how to predict on custom datasets

**Comment by KyanChen** [comment]
1. If you need to calculate the metrics, you should prepare your dataset in the coco data format. And follow the instructions in the readme, using tools/test.py script.
2. If you just need to inference on an image or a folder of images, please follow the instructions in the readme, using demo/image_demo.py script.

**Comment by 15926273249** [comment]
how to run the large_image_demo.py , what modifications should be made for the config files

**Comment by 15926273249** [comment]
AttributeError: 'ConfigDict' object has no attribute 'model' ，how to solve this problem

**Comment by funny000** [comment]
Hi@15926273249
请问你测试成功了吗
