### ISSUE TITLE
I have been unable to connect to the huggingface URL. Is there any other way without linking to the huggingface URL?

### ISSUE THREAD

**Issue by moderate-leon** [KyanChen/RSPrompter#78]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/sam-vit-base/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002228478E2B0>, 'Connection to huggingface.co timed out. (conne
ct timeout=10)'))
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\transformers\utils\hub.py", line 430, in cached_file
    resolved_file = hf_hub_download(
  File "D:\ProgramData\Anaconda3\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\huggingface_hub\file_download.py", line 1377, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like facebook/sam-vit-base is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

 Is there any other way without linking to the huggingface URL?

**Comment by zhanglimeng13** [comment]
I also encountered this problem and urgently need the author to solve it

**Comment by KyanChen** [comment]
https://zhuanlan.zhihu.com/p/646907543
