### ISSUE TITLE
作者您好，请问configs/rsprompter/samseg-maskrcnn-nwpu.py有freeze RSSamVisionEncoder吗？

### ISSUE THREAD

**Issue by wzr0108** [KyanChen/RSPrompter#79]
论文里1) SAM-seg: In SAM-seg, we make use of the knowledge present in SAM's image encoder while maintaining the cumbersome encoder frozen.
但是configs/rsprompter/samseg-maskrcnn-nwpu.py没看到freeze encoder

**Comment by pkyzh2006** [comment]
在SAMSegMaskRCNN里冻住了
