### ISSUE TITLE
The model and loaded state dict do not match exactly

### ISSUE THREAD

**Issue by Yisng** [KyanChen/RSPrompter#80]
![微信截图_20231212165015](https://github.com/KyanChen/RSPrompter/assets/91238418/e542a2b7-4f32-4902-8866-d3b18a9c4cf5)
![微信截图_20231212165056](https://github.com/KyanChen/RSPrompter/assets/91238418/84616dad-c578-4b9f-8fde-4667e817d2e7)
![微信截图_20231212165108](https://github.com/KyanChen/RSPrompter/assets/91238418/09780561-60f5-4c0d-a41d-236751c97b4f)
![微信截图_20231212165125](https://github.com/KyanChen/RSPrompter/assets/91238418/dc305db6-d31d-4c31-8c3c-fa91108e5512)

How to solve this problem.It's fine when I run python tools/train.py configs/my_config/samdet.py
but It's failing when I run python tools/train.py configs/my_config/samseg-mask2former.py

**Comment by jarvii218** [comment]
我也遇到了同样的问题...

**Comment by KyanChen** [comment]
pretrian_name不能用地址，只能用原来的，因为代码里面会解析用的是base还是huge，自己改了，就没办法解析出来用的哪个backbone了

**Comment by Feeeeeel** [comment]
那想问一下服务器连不上huggingface怎么办，只能用原来的的话没法自己下载上传了

**Comment by Feeeeeel** [comment]
I provide a method:

1. search “from_pretrained” in mmdet/models/repromter/models.py

2. change all the xxx.from_pretrained(hf_pretrain_name) into xxx.from_pretrained("<your_huggingface_offline_download_dir>/config.json")

3. modify the hf_sam_pretrain_ckpt_path to your pretrain model checkpoint in config

Then model runs successfully.
