### ISSUE TITLE
显存占用和模型准确度的问题

### ISSUE THREAD

**Issue by stivory** [KyanChen/RSPrompter#84]
之前的使用pytorch-lightning和mmdet版本(huggingface)的anchor-based的训练程序使用vit-h，我这边A800的batch-size能跑到4，
跑我这边的数据集的结果如下：
![image](https://github.com/KyanChen/RSPrompter/assets/109279053/7bfc602f-9850-4c7a-ae20-a0c2d0b09949)

现在使用mmdet实现的版本(release)的anchor-based的训练程序使用vit-h，A800的batch-size只能跑到2了。结果如下：
![image](https://github.com/KyanChen/RSPrompter/assets/109279053/3bc588db-55c1-4eb1-a9c7-3e6bab6b8a57)
结果差距并不是很大，但显存占用高了很多

**Comment by KyanChen** [comment]
新版本更改了方法
