### ISSUE TITLE
File download error-- not pytorch_model.bin but model.safetensors

### ISSUE THREAD

**Issue by qsd-github** [KyanChen/RSPrompter#85]
Using download_hf_sam_pretrain_ckpt.py file downloaded is a file called model.safetensors, not the pytorch_model.bin provided in the example_ model, how can I solve this problem?

**Comment by qsd-github** [comment]
I just checked the official website of Huggingface: huggingface.co, searched for the corresponding facebook/sam_vit_base, found the corresponding file, which contains pytorch_ model. bin, the perfect solution!

**Comment by SmirnoffAlexander** [comment]
You can also set use_safetensors flag to False in .from_pretrained() method

**Comment by KyanChen** [comment]
refer to  https://github.com/KyanChen/RSPrompter/blob/release/tools/rsprompter/download_hf_sam_pretrain_ckpt.py
