### ISSUE TITLE
lightning版的代码中用prompter-anchor进行训练验证时指标都没问题（AP60多），训练完成后用tools/predict.py和config里面的predict.py代码进行测试时，输出的结果一直是空（图像上面没有预测框和分割结果）。同样是在Vit-huge中加入一些可学习参数后，lightning版的代码训练速度没有慢多少，新版mmdet代码训练速度非常慢（在3090上nwpu数据集50个iter要40分钟，但用训练得到的权重测试的时候速度是正常的），这两个问题困扰我好长时间了，有大佬有代码在lightning版可以正常出预测结果吗？

### ISSUE THREAD

**Issue by moderate-leon** [KyanChen/RSPrompter#86]
![426](https://github.com/KyanChen/RSPrompter/assets/107356344/314378c6-6c92-4b58-a27b-6faf55a520fd)
左侧加载的标注信息中目标类别也只能显示class9，而不是car（数据集定义的地方是正确的）；右侧预测结果为空。

**Comment by pkyzh2006** [comment]
lighting版本我是训练和predict无问题，训练完后验证指标对不上，不是很清楚。作者说lighting版本有问题，也没去深究，用mmdet版本就是了，训练验证预测都没问题。至于训练慢的问题有点逗，我不去确定你是不是跟我一样的情况，你试着在backbone里加个peft_config=None看看。None本来是默认值，但是不加peft_config=None好像默认值不起作用，然后整个encoder就解锁了也参与训练。

**Comment by moderate-leon** [comment]
> lighting版本我是训练和predict无问题，训练完后验证指标对不上，不是很清楚。作者说lighting版本有问题，也没去深究，用mmdet版本就是了，训练验证预测都没问题。至于训练慢的问题有点逗，我不去确定你是不是跟我一样的情况，你试着在backbone里加个peft_config=None看看。None本来是默认值，但是不加peft_config=None好像默认值不起作用，然后整个encoder就解锁了也参与训练。

你用的lighting版本整体代码发给我一份呗，我看看我这能不能正常predict，感谢（邮箱：546641639@qq.com）

**Comment by pkyzh2006** [comment]
> > lighting版本我是训练和predict无问题，训练完后验证指标对不上，不是很清楚。作者说lighting版本有问题，也没去深究，用mmdet版本就是了，训练验证预测都没问题。至于训练慢的问题有点逗，我不去确定你是不是跟我一样的情况，你试着在backbone里加个peft_config=None看看。None本来是默认值，但是不加peft_config=None好像默认值不起作用，然后整个encoder就解锁了也参与训练。
> 
> 你用的lighting版本整体代码发给我一份呗，我看看我这能不能正常predict，感谢（邮箱：[546641639@qq.com](mailto:546641639@qq.com)）

就是之前这个库拉的代码。没改动

**Comment by funny000** [comment]
HI,@moderate-leon
你这个问题解决了吗

**Comment by pipashu1** [comment]
请问3090上的推理速度是多少 @moderate-leon

**Comment by funny000** [comment]
小图的话推理速度不慢，一个月前用的，印象中是不慢


2152550864
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KyanChen/RSPrompter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月9日(星期二) 下午4:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KyanChen/RSPrompter] lightning版的代码中用prompter-anchor进行训练验证时指标都没问题（AP60多），训练完成后用tools/predict.py和config里面的predict.py代码进行测试时，输出的结果一直是空（图像上面没有预测框和分割结果）。同样是在Vit-huge中加入一些可学习参数后，lightning版的代码训练速度没有慢多少，新版mmdet代�= A0�训练速度非常慢（在3090上nwpu数据集50个iter要40分钟，但用训练得到的权重测试的时候速度是正常的），这两个问题困扰我好长时间了，有大佬有代码在lightning版可以正常出预测结果吗？ (Issue #86)





 
请问3090上的推理速度是多少 @moderate-leon

**Comment by ymkasad** [comment]
> ![426](https://private-user-images.githubusercontent.com/107356344/292759290-314378c6-6c92-4b58-a27b-6faf55a520fd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MTAzMjksIm5iZiI6MTcxNzkxMDAyOSwicGF0aCI6Ii8xMDczNTYzNDQvMjkyNzU5MjkwLTMxNDM3OGM2LTZjOTItNGI1OC1hMjdiLTZmYWY1NWE1MjBmZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQwNTEzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWEwNzFiMWNkZTJhMGU5NjRlOGYxYTFmOWZhN2YyNTNlOWQ3YTVlZTM0MGZjM2IwODEyZmYxOTFmMzRlNTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R4Oe34Vo8_xJR9uGU0ebtnHWV7T6vvEDb0DH6ojU4yU) 左侧加载的标注信息中目标类别也只能显示class9，而不是car（数据集定义的地方是正确的）；右侧预测结果为空。
你好，这个预测没有结果，请问你解决这个问题了吗

**Comment by KyanChen** [comment]
请更换mmdet版本
