### ISSUE TITLE
有同学尝试将训练的模型转为onnx的吗

### ISSUE THREAD

**Issue by Jinunmeng** [KyanChen/RSPrompter#87]
![1](https://github.com/KyanChen/RSPrompter/assets/13739181/f11c3a4e-c446-47d3-ab27-7d55609c0706)
![2](https://github.com/KyanChen/RSPrompter/assets/13739181/90770df5-95e7-4404-9677-95f35d2cb98b)
使用作者的框架训练结果，还是比较满意的，请问有将模型转为onnx的吗

**Comment by funny000** [comment]
请问这个模型可以识别哪几种地物类别？

**Comment by Jinunmeng** [comment]
> 请问这个模型可以识别哪几种地物类别？

我只标注一个地块类的，你也可以标注多个类来训练模型

**Comment by funny000** [comment]
了解了，训练起来快吗，一个epoch大概多长时间，24G内存可以训起来吗

**Comment by funny000** [comment]
请问你安装的时候遇到过 failed to import mmdet.rsprompter这个问题吗

**Comment by funny000** [comment]
> > 请问这个模型可以识别哪几种地物类别？
> 
> 我只标注一个地块类的，你也可以标注多个类来训练模型

老哥，用自己的数据集生成anchor的时候，是生成HBB框还是地物的边框好？比如你上面那个耕地，水平框的里面除了耕地还有背景，这种情况对训练或预测影响大吗
