### ISSUE TITLE
怎么没找到将DeepSpeed训练的模型转换为MMDetection的模型的代码 ‘’zero_to_fp32.py‘’在哪啊

### ISSUE THREAD

**Issue by moderate-leon** [KyanChen/RSPrompter#88]
![picture](https://github.com/KyanChen/RSPrompter/assets/107356344/2c9a111f-55d2-4b8b-b1d4-9d7c71be96bb)

**Comment by KyanChen** [comment]
在保存ckpt的文件夹中
