### ISSUE TITLE
使用image_demo图像预测的问题

### ISSUE THREAD

**Issue by cricket-111** [KyanChen/RSPrompter#89]
在使用原代码RSPrompter-cky训练得到的权重文件.ckpt，直接使用的image_demo.py预测输出时，无法输出得到正确的预测图片，请问您是否遇到过类似的问题，知道如何解决吗
![2_8](https://github.com/KyanChen/RSPrompter/assets/56532880/0dc7e54d-00d2-41e8-8638-a8ffd399b5ae)

**Comment by 1205078294** [comment]
您好，我也遇到了和您同样的问题，请问您现在有解决方法了吗？

**Comment by cricket-111** [comment]
> 您好，我也遇到了和您同样的问题，请问您现在有解决方法了吗？
没有，我现在用的还是旧的框架进行预测的

**Comment by 1205078294** [comment]
> > 您好，我也遇到了和您同样的问题，请问您现在有解决方法了吗？
> > 没有，我现在用的还是旧的框架进行预测的

您的意思是您用的是之前版本的RSPrompter，还是您放弃使用了这个方法？

**Comment by cricket-111** [comment]
使用之前的版本RSPrompter-cky

**Comment by cricket-111** [comment]
> > > 您好，我也遇到了和您同样的问题，请问您现在有解决方法了吗？
> > > 没有，我现在用的还是旧的框架进行预测的
> 
> 您的意思是您用的是之前版本的RSPrompter，还是您放弃使用了这个方法？

使用之前的版本RSPrompter-cky

**Comment by 1205078294** [comment]
您好，我现在遇到了困难，我想请教一下您。使用之前的cky版本，应该怎么进行单张图片的预测？我现在已经可以跑通train，test，predict代码，但是单张的图片的预测无从下手，是要自己写一个代码吗？

**Comment by cricket-111** [comment]
> 您好，我现在遇到了困难，我想请教一下您。使用之前的cky版本，应该怎么进行单张图片的预测？我现在已经可以跑通train，test，predict代码，但是单张的图片的预测无从下手，是要自己写一个代码吗？

可以看一下已经被关闭的第51个问题，有位大佬写了如何预测
![image](https://github.com/KyanChen/RSPrompter/assets/56532880/3b4dabde-9141-41ea-a28a-6ad645561683)

**Comment by KyanChen** [comment]
请参考新版
