### ISSUE TITLE
torch.cuda.Out Of Memory Error: CUDA out of memory.  

### ISSUE THREAD

**Issue by ZhaoPo** [KyanChen/RSPrompter#9]
Hello, I have encountered the problem of CUDA out of memory in training, do you have any solution for me, thank you.

for example：
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 11.76 GiB total capacity; 9.88 GiB already allocated; 69.12 MiB free; 10.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by KyanChen** [comment]
You can try batchsize = 1

**Comment by KyanChen** [comment]
or use the base vit model

**Comment by KyanChen** [comment]
thank you
