### ISSUE TITLE
关于LoRA高效微调方法使得输入图像尺寸可变的问题

### ISSUE THREAD

**Issue by sleepat-11** [KyanChen/RSPrompter#91]
作者您好，感谢您的工作。我在readme更新日志中看到： 
"2023.11.26 加入了LoRA高效微调方法，并使得输入图像尺寸可变，减小了模型的显存占用。"
我想问一下在哪可以看到相关的文件或者改进？我知道的是sam预训练模型是在1024*1024上预训练的，如何使得输入图像尺寸可变？谢谢！

**Comment by KJXXbear** [comment]
"configs\rsprompter\rsprompter_query-nwpu-peft-512.py"作者没时间回，你看看这个配置文件吧，应该能回答你的问题
