### ISSUE TITLE
请问当用一个本地数据集微调的时候，模型的泛化性是不是会降低？

### ISSUE THREAD

**Issue by funny000** [KyanChen/RSPrompter#94]
感谢作者开源，
最近在做建筑物提取，本地有一个数据集，在微调sam-maskrcnn，微调完这个模型在其他区域也能提取建筑物吗，泛化性和精度会降低吗

**Comment by ymkasad** [comment]
你好，请问为什么我用maskrcnn去训练，然后用image_demo得不到预测结果呀，你又遇到类似问题吗

**Comment by KyanChen** [comment]
> 感谢作者开源， 最近在做建筑物提取，本地有一个数据集，在微调sam-maskrcnn，微调完这个模型在其他区域也能提取建筑物吗，泛化性和精度会降低吗

可以尝试下在新数据上推理

**Comment by KyanChen** [comment]
> 你好，请问为什么我用maskrcnn去训练，然后用image_demo得不到预测结果呀，你又遇到类似问题吗

得看下具体问题
