### ISSUE TITLE
我的损失一开始收敛，但是很快就变成NaN了，我想知道这可能是什么原因

### ISSUE THREAD

**Issue by 21-10-4** [KyanChen/RSPrompter#95]
这是我的损失曲线：
![image](https://github.com/KyanChen/RSPrompter/assets/91857689/1ebf0e7d-20ec-487e-9a11-338062cf3088)
我的训练代码：
```sh ./tools/dist_train.sh  configs/rsprompter/rsprompter_anchor-nwpu.py 2```
除此之外，由于我的卡只有11G，所以我修改了py配置文件：
```crop_size = (512, 512)
extra_config=dict(output_hidden_states=True, image_size=512)
```

**Comment by DAIJinJ** [comment]
请问解决了吗

**Comment by DAIJinJ** [comment]
> 这是我的损失曲线： ![image](https://private-user-images.githubusercontent.com/91857689/313084024-1ebf0e7d-20ec-487e-9a11-338062cf3088.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODU0NzIsIm5iZiI6MTcxNDk4NTE3MiwicGF0aCI6Ii85MTg1NzY4OS8zMTMwODQwMjQtMWViZjBlN2QtMjBlYy00ODdlLTlhMTEtMzM4MDYyY2YzMDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA4NDYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZWZmODFjY2RmNWZlNjEwMjIyZDJhYjM3YTIyODYyZWVlNjVhYjRlNjRjN2U5ODVmNjU2MTdmMDNhMTQzZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hn4QcdgTY3xdDJxdbypYio-wAkVdxz7er-UBZTtoFHo) 我的训练代码： `sh ./tools/dist_train.sh configs/rsprompter/rsprompter_anchor-nwpu.py 2` 除此之外，由于我的卡只有11G，所以我修改了py配置文件：
> 
> ```
> extra_config=dict(output_hidden_states=True, image_size=512)
> ```

请问解决了吗

**Comment by KyanChen** [comment]
fixed: 请查看QA中的第6条。见 https://github.com/KyanChen/RSPrompter/blob/release/README_zh-CN.md
