### ISSUE TITLE
no pos rois

### ISSUE THREAD

**Issue by AImagicAI** [KyanChen/RSPrompter#96]
您好，我的训练样本不存在空的标注，但出现了如下报错，请问如何排查解决呢？谢谢！
no pos rois
no pos rois
no pos rois
no pos rois
no pos rois
no pos rois
no pos rois
no pos rois
no pos rois
no pos rois
03/29 15:53:20 - mmengine - INFO - Epoch(train)   [1][   10/11841]  lr: 3.6898e-05  eta: 50 days, 13:22:46  time: 0.6148  data_time: 0.0121  memory: 9385  loss: 2.7195  loss_rpn_cls: 0.6839  loss_rpn_bbox: 0.0000  loss_cls: 2.0356  acc: 100.0000  loss_bbox: 0.0000  loss_mask: 0.0000
no pos rois
no pos rois
no pos rois
no pos rois
no pos rois
no pos rois
no pos rois
no pos rois
no pos rois
no pos rois
03/29 15:53:24 - mmengine - INFO - Epoch(train)   [1][   20/11841]  lr: 7.7673e-05  eta: 45 days, 2:01:11  time: 0.5483  data_time: 0.0074  memory: 9380  loss: 1.6773  loss_rpn_cls: 0.6477  loss_rpn_bbox: 0.0000  loss_cls: 1.0296  acc: 100.0000  loss_bbox: 0.0000  loss_mask: 0.0000
no pos rois
no pos rois
no pos rois
no pos rois
no pos rois
no pos rois
no pos rois
no pos rois
no pos rois
no pos rois
03/29 15:53:29 - mmengine - INFO - Epoch(train)   [1][   30/11841]  lr: 1.1845e-04  eta: 43 days, 5:55:24  time: 0.5259  data_time: 0.0057  memory: 9380  loss: 1.2351  loss_rpn_cls: 0.5487  loss_rpn_bbox: 0.0000  loss_cls: 0.6864  acc: 100.0000  loss_bbox: 0.0000  loss_mask: 0.0000

**Comment by KyanChen** [comment]
这不还在训吗？没看到报错呀

**Comment by AImagicAI** [comment]
loss_rpn_bbox: 0.0000， acc: 100.0000， loss_bbox: 0.0000 loss_mask: 0.0000
这几个数值正确吗？acc一直为100，这几个loss一直为0？

**Comment by AImagicAI** [comment]
loss_rpn_bbox: 0.0000， acc: 100.0000， loss_bbox: 0.0000 loss_mask: 0.0000
 这几个数值正确吗？acc一直为100，这几个loss一直为0？


                       
原始邮件
                       
                     

发件人："Keyan Chen"< ***@***.*** &gt;;

发件时间：2024/3/29 16:55

收件人："KyanChen/RSPrompter"< ***@***.*** &gt;;

抄送人："AImagicAI"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [KyanChen/RSPrompter] no pos rois (Issue #96)




 
这不还在训吗？没看到报错呀

**Comment by AImagicAI** [comment]
并且迭代几次后，出现这种情况：


03/29 16:58:46 - mmengine - INFO - Epoch(train) &nbsp; [1][ &nbsp;130/11841] &nbsp;lr: 2.0000e-04 &nbsp;eta: 40 days, 7:12:10 &nbsp;time: 0.4786 &nbsp;data_time: 0.0025 &nbsp;memory: 9381 &nbsp;loss: 0.0001 &nbsp;loss_rpn_cls: 0.0001 &nbsp;loss_rpn_bbox: 0.0000 &nbsp;loss_cls: 0.0000 &nbsp;acc: 100.0000 &nbsp;loss_bbox: 0.0000 &nbsp;loss_mask: 0.0000
&nbsp;


loss全为0了。







                       
原始邮件
                       
                     

发件人："Keyan Chen"< ***@***.*** &gt;;

发件时间：2024/3/29 16:55

收件人："KyanChen/RSPrompter"< ***@***.*** &gt;;

抄送人："AImagicAI"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [KyanChen/RSPrompter] no pos rois (Issue #96)




 
这不还在训吗？没看到报错呀

**Comment by KyanChen** [comment]
我建议你先用nwpu数据集试试

**Comment by KyanChen** [comment]
把学习率改小试试

**Comment by AImagicAI** [comment]
学习率改小，还是同样问题。我尝试用SSDD数据集，跑一下模型。但是，项目ssdd数据集链接不是SSDD数据集。可以发一下相应SSDD数据集吗？谢谢！








                       
原始邮件
                       
                     

发件人："Keyan Chen"< ***@***.*** &gt;;

发件时间：2024/3/29 17:02

收件人："KyanChen/RSPrompter"< ***@***.*** &gt;;

抄送人："AImagicAI"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [KyanChen/RSPrompter] no pos rois (Issue #96)




 
把学习率改小试试

**Comment by AImagicAI** [comment]
我用SSDD数据集是可以正常训练的，但是用自己数据集，一直出现之前的情况。一直未排查到原因。







                       
原始邮件
                       
                     

发件人："Keyan Chen"< ***@***.*** &gt;;

发件时间：2024/3/29 17:02

收件人："KyanChen/RSPrompter"< ***@***.*** &gt;;

抄送人："AImagicAI"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [KyanChen/RSPrompter] no pos rois (Issue #96)




 
把学习率改小试试

**Comment by wwlaoxi** [comment]
我用whu数据集训练正常，但是用自己的数据集训练也出现了no pos rois，怎么解决呢？

**Comment by wwlaoxi** [comment]
我用whu数据集训练正常，但是用自己的数据集训练也出现了no pos rois，怎么解决呢？
