### ISSUE TITLE
目前用建筑数据集和自己的数据集生成的训练json文件，模型可以跑起来，但是bboxloss一直为零，用自带的nwpu的训练集，bboxloss不为零，模型能正常收敛，有老师遇到过吗

### ISSUE THREAD

**Issue by funny000** [KyanChen/RSPrompter#97]

**Comment by AImagicAI** [comment]
同样的情况，未找到解决方案

**Comment by funny000** [comment]
你好，你用的什么数据集，我考虑了下，有可能是我的数据集问题，论文的语义分割数据集是一个图片上目标的边框都在图片里面，不是边界上，我的数据集是边框在边界上，
这是nwpu的数据集，比如飞机的边框在图片里面，掩码也是在里面，https://pic4.zhimg.com/80/v2-f0ee9e6ec80336e67241845a957655e7_1440w.webp
我的数据集是一个图上，比如水体，从0.0坐标沿着边界到100.100坐标都是水体




2152550864
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KyanChen/RSPrompter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月9日(星期二) 上午10:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KyanChen/RSPrompter] 目前用建筑数据集和自己的数据集生成的训练json文件，模型可以跑起来，但是bboxloss一直为零，用自带的nwpu的训练集，bboxloss不为零，模型能正常收敛，有老师遇到过吗 (Issue #97)





 
同样的情况，未找到解决方案

**Comment by AImagicAI** [comment]
您好，我用自己的数据集，只有部分在边界的情况？请问，这是原因吗？您修改后，可以正常训练了吗？




                       
原始邮件
                       
                     

发件人："poplar"< ***@***.*** &gt;;

发件时间：2024/4/9 11:44

收件人："KyanChen/RSPrompter"< ***@***.*** &gt;;

抄送人："AImagicAI"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [KyanChen/RSPrompter] 目前用建筑数据集和自己的数据集生成的训练json文件，模型可以跑起来，但是bboxloss一直为零，用自带的nwpu的训练集，bboxloss不为零，模型能正常收敛，有老师遇到过吗 (Issue #97)




 你好，你用的什么数据集，我考虑了下，有可能是我的数据集问题，论文的语义分割数据集是一个图片上目标的边框都在图片里面，不是边界上，我的数据集是边框在边界上， 
 这是nwpu的数据集，比如飞机的边框在图片里面，掩码也是在里面，https://pic4.zhimg.com/80/v2-f0ee9e6ec80336e67241845a957655e7_1440w.webp 
 我的数据集是一个图上，比如水体，从0.0坐标沿着边界到100.100坐标都是水体 
 
 
 
 
 2152550864 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "KyanChen/RSPrompter"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年4月9日(星期二) 上午10:35 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [KyanChen/RSPrompter] 目前用建筑数据集和自己的数据集生成的训练json文件，模型可以跑起来，但是bboxloss一直为零，用自带的nwpu的训练集，bboxloss不为零，模型能正常收敛，有老师遇到过吗 (Issue #97) 
 
 
 
 
 
   
 同样的情况，未找到解决方案

**Comment by funny000** [comment]
我考虑是因为无法回归bbox坐标，所以训练时候bboxloss一直为零，所以模型效果不好，现在手头没有多余的数据集可以测试，所以还没验证这个猜想




2152550864
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KyanChen/RSPrompter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月10日(星期三) 中午1:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KyanChen/RSPrompter] 目前用建筑数据集和自己的数据集生成的训练json文件，模型可以跑起来，但是bboxloss一直为零，用自带的nwpu的训练集，bboxloss不为零，模型能正常收敛，有老师遇到过吗 (Issue #97)





 您好，我用自己的数据集，只有部分在边界的情况？请问，这是原因吗？您修改后，可以正常训练了吗？ 
 
 
 
 
                         
 原始邮件 
                         
                       
 
 发件人："poplar"< ***@***.*** &amp;gt;; 
 
 发件时间：2024/4/9 11:44 
 
 收件人："KyanChen/RSPrompter"< ***@***.*** &amp;gt;; 
 
 抄送人："AImagicAI"< ***@***.*** &amp;gt;;"Comment"< ***@***.*** &amp;gt;; 
 
 主题：Re: [KyanChen/RSPrompter] 目前用建筑数据集和自己的数据集生成的训练json文件，模型可以跑起来，但是bboxloss一直为零，用自带的nwpu的训练集，bboxloss不为零，模型能正常收敛，有老师遇到过吗 (Issue #97) 
 
 
 
 
  你好，你用的什么数据集，我考虑了下，有可能是我的数据集问题，论文的语义分割数据集是一个图片上目标的边框都在图片里面，不是边界上，我的数据集是边框在边界上，  
  这是nwpu的数据集，比如飞机的边框在图片里面，掩码也是在里面，https://pic4.zhimg.com/80/v2-f0ee9e6ec80336e67241845a957655e7_1440w.webp  
  我的数据集是一个图上，比如水体，从0.0坐标沿着边界到100.100坐标都是水体  
   
   
   
   
  2152550864  
  ***@***.***  
   
   
   
  &amp;amp;nbsp;  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "KyanChen/RSPrompter"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2024年4月9日(星期二) 上午10:35  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [KyanChen/RSPrompter] 目前用建筑数据集和自己的数据集生成的训练json文件，模型可以跑起来，但是bboxloss一直为零，用自带的nwpu的训练集，bboxloss不为零，模型能正常收敛，有老师遇到过吗 (Issue #97)  
   
   
   
   
   
     
  同样的情况，未找到解决方案

**Comment by AImagicAI** [comment]
您好，现在您解决这个问题了吗？


                       
原始邮件
                       
                     

发件人："poplar"< ***@***.*** &gt;;

发件时间：2024/4/13 11:01

收件人："KyanChen/RSPrompter"< ***@***.*** &gt;;

抄送人："AImagicAI"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [KyanChen/RSPrompter] 目前用建筑数据集和自己的数据集生成的训练json文件，模型可以跑起来，但是bboxloss一直为零，用自带的nwpu的训练集，bboxloss不为零，模型能正常收敛，有老师遇到过吗 (Issue #97)




 我考虑是因为无法回归bbox坐标，所以训练时候bboxloss一直为零，所以模型效果不好，现在手头没有多余的数据集可以测试，所以还没验证这个猜想 
 
 
 
 
 2152550864 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "KyanChen/RSPrompter"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年4月10日(星期三) 中午1:37 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [KyanChen/RSPrompter] 目前用建筑数据集和自己的数据集生成的训练json文件，模型可以跑起来，但是bboxloss一直为零，用自带的nwpu的训练集，bboxloss不为零，模型能正常收敛，有老师遇到过吗 (Issue #97) 
 
 
 
 
 
  您好，我用自己的数据集，只有部分在边界的情况？请问，这是原因吗？您修改后，可以正常训练了吗？  
   
   
   
   
                           
  原始邮件  
                           
                         
   
  发件人："poplar"< ***@***.*** &amp;amp;gt;;  
   
  发件时间：2024/4/9 11:44  
   
  收件人："KyanChen/RSPrompter"< ***@***.*** &amp;amp;gt;;  
   
  抄送人："AImagicAI"< ***@***.*** &amp;amp;gt;;"Comment"< ***@***.*** &amp;amp;gt;;  
   
  主题：Re: [KyanChen/RSPrompter] 目前用建筑数据集和自己的数据集生成的训练json文件，模型可以跑起来，但是bboxloss一直为零，用自带的nwpu的训练集，bboxloss不为零，模型能正常收敛，有老师遇到过吗 (Issue #97)  
   
   
   
   
   你好，你用的什么数据集，我考虑了下，有可能是我的数据集问题，论文的语义分割数据集是一个图片上目标的边框都在图片里面，不是边界上，我的数据集是边框在边界上，   
   这是nwpu的数据集，比如飞机的边框在图片里面，掩码也是在里面，https://pic4.zhimg.com/80/v2-f0ee9e6ec80336e67241845a957655e7_1440w.webp   
   我的数据集是一个图上，比如水体，从0.0坐标沿着边界到100.100坐标都是水体   
     
     
     
     
   2152550864   
   ***@***.***   
     
     
     
   &amp;amp;amp;nbsp;   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "KyanChen/RSPrompter"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2024年4月9日(星期二) 上午10:35   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [KyanChen/RSPrompter] 目前用建筑数据集和自己的数据集生成的训练json文件，模型可以跑起来，但是bboxloss一直为零，用自带的nwpu的训练集，bboxloss不为零，模型能正常收敛，有老师遇到过吗 (Issue #97)   
     
     
     
     
     
       
   同样的情况，未找到解决方案

**Comment by KyanChen** [comment]
fixed: 请查看QA中的第6条。见 https://github.com/KyanChen/RSPrompter/blob/release/README_zh-CN.md
