### ISSUE TITLE
loss=0

### ISSUE THREAD

**Issue by AImagicAI** [KyanChen/RSPrompter#98]
![图片](https://github.com/KyanChen/RSPrompter/assets/164443911/7112db87-be7b-44e5-8137-22b03013ffd3)
 
您好，我在训练自己数据集时，loss=0。

04/10 14:42:49 - mmengine - INFO - Epoch(train)   [1][   50/11841]  lr: 2.0000e-04  eta: 17 days, 5:39:40  time: 0.5031  data_time: 0.0056  memory: 9182  loss: 0.8814  loss_rpn_cls: 0.3083  loss_rpn_bbox: 0.0000  loss_cls: 0.5731  acc: 100.0000  loss_bbox: 0.0000  loss_mask: 0.0000
04/10 14:42:54 - mmengine - INFO - Epoch(train)   [1][   60/11841]  lr: 2.0000e-04  eta: 17 days, 1:57:52  time: 0.4753  data_time: 0.0024  memory: 9182  loss: 0.2264  loss_rpn_cls: 0.1712  loss_rpn_bbox: 0.0000  loss_cls: 0.0552  acc: 100.0000  loss_bbox: 0.0000  loss_mask: 0.0000
04/10 14:42:58 - mmengine - INFO - Epoch(train)   [1][   70/11841]  lr: 2.0000e-04  eta: 17 days, 0:31:02  time: 0.4774  data_time: 0.0024  memory: 9182  loss: 0.0565  loss_rpn_cls: 0.0565  loss_rpn_bbox: 0.0000  loss_cls: 0.0000  acc: 100.0000  loss_bbox: 0.0000  loss_mask: 0.0000
04/10 14:43:03 - mmengine - INFO - Epoch(train)   [1][   80/11841]  lr: 2.0000e-04  eta: 16 days, 23:08:44  time: 0.4789  data_time: 0.0025  memory: 9182  loss: 0.0067  loss_rpn_cls: 0.0067  loss_rpn_bbox: 0.0000  loss_cls: 0.0000  acc: 100.0000  loss_bbox: 0.0000  loss_mask: 0.0000
04/10 14:43:08 - mmengine - INFO - Epoch(train)   [1][   90/11841]  lr: 2.0000e-04  eta: 16 days, 21:24:56  time: 0.4792  data_time: 0.0026  memory: 9182  loss: 0.0006  loss_rpn_cls: 0.0006  loss_rpn_bbox: 0.0000  loss_cls: 0.0000  acc: 100.0000  loss_bbox: 0.0000  loss_mask: 0.0000
04/10 14:43:13 - mmengine - INFO - Epoch(train)   [1][  100/11841]  lr: 2.0000e-04  eta: 16 days, 20:03:36  time: 0.4797  data_time: 0.0027  memory: 9182  loss: 0.0002  loss_rpn_cls: 0.0002  loss_rpn_bbox: 0.0000  loss_cls: 0.0000  acc: 100.0000  loss_bbox: 0.0000  loss_mask: 0.0000
04/10 14:43:18 - mmengine - INFO - Epoch(train)   [1][  110/11841]  lr: 2.0000e-04  eta: 16 days, 18:54:51  time: 0.4797  data_time: 0.0027  memory: 9182  loss: 0.0002  loss_rpn_cls: 0.0002  loss_rpn_bbox: 0.0000  loss_cls: 0.0000  acc: 100.0000  loss_bbox: 0.0000  loss_mask: 0.0000
04/10 14:43:22 - mmengine - INFO - Epoch(train)   [1][  120/11841]  lr: 2.0000e-04  eta: 16 days, 17:53:47  time: 0.4775  data_time: 0.0026  memory: 9182  loss: 0.0001  loss_rpn_cls: 0.0001  loss_rpn_bbox: 0.0000  loss_cls: 0.0000  acc: 100.0000  loss_bbox: 0.0000  loss_mask: 0.0000
04/10 14:43:27 - mmengine - INFO - Epoch(train)   [1][  130/11841]  lr: 2.0000e-04  eta: 16 days, 17:06:29  time: 0.4761  data_time: 0.0026  memory: 9182  loss: 0.0001  loss_rpn_cls: 0.0001  loss_rpn_bbox: 0.0000  loss_cls: 0.0000  acc: 100.0000  loss_bbox: 0.0000  loss_mask: 0.0000
04/10 14:43:32 - mmengine - INFO - Epoch(train)   [1][  140/11841]  lr: 2.0000e-04  eta: 16 days, 16:18:34  time: 0.4757  data_time: 0.0026  memory: 9182  loss: 0.0001  loss_rpn_cls: 0.0001  loss_rpn_bbox: 0.0000  loss_cls: 0.0000  acc: 100.0000  loss_bbox: 0.0000  loss_mask: 0.0000
04/10 14:43:37 - mmengine - INFO - Epoch(train)   [1][  150/11841]  lr: 2.0000e-04  eta: 16 days, 15:42:11  time: 0.4755  data_time: 0.0026  memory: 9182  loss: 0.0001  loss_rpn_cls: 0.0001  loss_rpn_bbox: 0.0000  loss_cls: 0.0000  acc: 100.0000  loss_bbox: 0.0000  loss_mask: 0.0000
04/10 14:43:41 - mmengine - INFO - Epoch(train)   [1][  160/11841]  lr: 2.0000e-04  eta: 16 days, 15:11:23  time: 0.4755  data_time: 0.0026  memory: 9182  loss: 0.0001  loss_rpn_cls: 0.0001  loss_rpn_bbox: 0.0000  loss_cls: 0.0000  acc: 100.0000  loss_bbox: 0.0000  loss_mask: 0.0000

**Comment by lphilomena** [comment]
你好！我也遇到了同样的问题，请问你解决这个问题了吗？

**Comment by KyanChen** [comment]
fixed: 请查看QA中的第6条。见 https://github.com/KyanChen/RSPrompter/blob/release/README_zh-CN.md
