### ISSUE TITLE
在使用demo.py中自带图片进行预测时，输出文件夹无法访问，或者缺少参数

### ISSUE THREAD

**Issue by hailongm** [KyanChen/RSPrompter#99]
在输入预测命令行后，出现下述两种不同的报错，如何解决
![a3f6ca14446dadf7fc221bc448132974](https://github.com/KyanChen/RSPrompter/assets/145880664/f10eeb4b-4819-44cc-8914-2ce8f644a40d)
![f0410e5154d67f31380bf184b58f14d8](https://github.com/KyanChen/RSPrompter/assets/145880664/fe7f147c-e965-4476-9e3d-8f87d00a771a)

**Comment by KyanChen** [comment]
命令错误
